// <auto-generated />
using System;
using AlSsareea.Modules.Orders.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Orders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260802214051_InitializeOrdersModule")]
    partial class InitializeOrdersModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<string>("CancellationCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cancellation_code");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<short?>("CancelledBy")
                        .HasColumnType("smallint")
                        .HasColumnName("cancelled_by");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<long>("CouponDiscountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("coupon_discount_minor");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_notes");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<long>("DeliveryDiscountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_discount_minor");

                    b.Property<long>("DeliveryFeeMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_fee_minor");

                    b.Property<DateTime?>("DriverAssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("driver_assigned_at_utc");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<Guid?>("MerchantBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_branch_id");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("MerchantNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("merchant_notes");

                    b.Property<long>("OptionsTotalMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("options_total_minor");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_number");

                    b.Property<DateTime?>("PickedUpAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at_utc");

                    b.Property<long>("PlatformFeeMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_fee_minor");

                    b.Property<DateTime?>("PreparingAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preparing_at_utc");

                    b.Property<DateTime>("PricingCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pricing_calculated_at_utc");

                    b.Property<string>("PricingReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("pricing_reference");

                    b.Property<long>("ProductDiscountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("product_discount_minor");

                    b.Property<DateTime?>("ReadyForPickupAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_for_pickup_at_utc");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at_utc");

                    b.Property<DateTime?>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<long>("ServiceFeeMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("service_fee_minor");

                    b.Property<long>("SmallOrderFeeMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("small_order_fee_minor");

                    b.Property<Guid>("SourceCartId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_cart_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("subtotal_minor");

                    b.Property<long>("TaxMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("tax_minor");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("total_minor");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_orders_created_at_utc");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("MerchantBranchId")
                        .HasDatabaseName("ix_orders_merchant_branch_id");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_orders_merchant_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_order_number");

                    b.HasIndex("ScheduledForUtc")
                        .HasDatabaseName("ix_orders_scheduled_for_utc");

                    b.HasIndex("SourceCartId")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_source_cart_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.HasIndex("CustomerId", "CreatedAtUtc")
                        .HasDatabaseName("ix_orders_customer_created");

                    b.HasIndex("MerchantId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_orders_merchant_status_created");

                    b.ToTable("orders", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_orders_currency", "char_length(currency) = 3");

                            t.HasCheckConstraint("ck_orders_money_non_negative", "subtotal_minor >= 0 AND options_total_minor >= 0 AND product_discount_minor >= 0 AND coupon_discount_minor >= 0 AND delivery_discount_minor >= 0 AND delivery_fee_minor >= 0 AND service_fee_minor >= 0 AND platform_fee_minor >= 0 AND small_order_fee_minor >= 0 AND tax_minor >= 0 AND total_minor >= 0");

                            t.HasCheckConstraint("ck_orders_scheduled", "scheduled_for_utc IS NULL OR scheduled_for_utc > created_at_utc");

                            t.HasCheckConstraint("ck_orders_total", "total_minor = subtotal_minor + delivery_fee_minor + service_fee_minor + platform_fee_minor + small_order_fee_minor + tax_minor - product_discount_minor - coupon_discount_minor - delivery_discount_minor");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_note");

                    b.Property<long>("LineDiscountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("line_discount_minor");

                    b.Property<long>("LineSubtotalMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("line_subtotal_minor");

                    b.Property<long>("LineTotalMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("line_total_minor");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_name");

                    b.Property<int>("ProductVersion")
                        .HasColumnType("integer")
                        .HasColumnName("product_version");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("sku");

                    b.Property<long>("UnitBasePriceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_base_price_minor");

                    b.Property<long>("UnitDiscountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_discount_minor");

                    b.Property<long>("UnitFinalPriceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_final_price_minor");

                    b.Property<long>("UnitOptionsPriceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_options_price_minor");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("VariantName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("variant_name");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.ToTable("order_items", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_items_money", "unit_base_price_minor >= 0 AND unit_options_price_minor >= 0 AND unit_discount_minor >= 0 AND unit_final_price_minor >= 0 AND line_subtotal_minor >= 0 AND line_discount_minor >= 0 AND line_total_minor >= 0");

                            t.HasCheckConstraint("ck_order_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.OrderItemOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OptionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_group_id");

                    b.Property<string>("OptionGroupName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("option_group_name");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("option_name");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("TotalPriceAdjustmentMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("total_price_adjustment_minor");

                    b.Property<long>("UnitPriceAdjustmentMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price_adjustment_minor");

                    b.HasKey("Id")
                        .HasName("pk_order_item_options");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_order_item_options_order_item_id");

                    b.ToTable("order_item_options", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_item_options_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("ChangeSource")
                        .HasColumnType("smallint")
                        .HasColumnName("change_source");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<short>("NewStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("new_status");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<short?>("PreviousStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("previous_status");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason_text");

                    b.HasKey("Id")
                        .HasName("pk_order_status_history");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_status_history_order_id");

                    b.HasIndex("OrderId", "ChangedAtUtc")
                        .HasDatabaseName("ix_order_status_history_order_changed");

                    b.ToTable("order_status_history", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_status_history_changed", "previous_status IS NULL OR previous_status <> new_status");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Infrastructure.Persistence.OrderCreationIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.HasKey("Id")
                        .HasName("pk_order_creation_idempotency");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_order_creation_idempotency_order_id");

                    b.HasIndex("CustomerId", "Operation", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_order_creation_idempotency_customer_operation_key");

                    b.ToTable("order_creation_idempotency", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_creation_idempotency_hashes", "char_length(key_hash) = 64 AND char_length(request_hash) = 64");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Infrastructure.Persistence.OrderOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_order_outbox_messages");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_order_outbox_occurred_at_utc");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_order_outbox_processed_at_utc");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_order_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_order_outbox_event_type", "char_length(event_type) > 0");

                            t.HasCheckConstraint("ck_order_outbox_payload", "jsonb_typeof(payload) = 'object'");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.Order", b =>
                {
                    b.OwnsOne("AlSsareea.Modules.Orders.Domain.CustomerSnapshot", "Customer", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("snapshot_customer_id");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("customer_display_name");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("customer_phone_number");

                            b1.Property<string>("PreferredLanguage")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("customer_preferred_language");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Orders.Domain.DeliveryAddressSnapshot", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid")
                                .HasColumnName("address_id");

                            b1.Property<string>("Apartment")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("address_apartment");

                            b1.Property<string>("Area")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("address_area");

                            b1.Property<string>("BuildingNumber")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("address_building_number");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("address_city");

                            b1.Property<string>("DeliveryInstructions")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("address_delivery_instructions");

                            b1.Property<string>("Floor")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("address_floor");

                            b1.Property<string>("FormattedAddress")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("address_formatted");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("address_label");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("PlaceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_place_id");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("address_street");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Orders.Domain.MerchantSnapshot", "Merchant", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("BranchAddress")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("branch_address");

                            b1.Property<string>("BranchDisplayName")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("branch_display_name");

                            b1.Property<Guid?>("BranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("snapshot_branch_id");

                            b1.Property<string>("BranchPhoneNumber")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("branch_phone_number");

                            b1.Property<string>("MerchantDisplayName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("merchant_display_name");

                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid")
                                .HasColumnName("snapshot_merchant_id");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("Merchant")
                        .IsRequired();
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.OrderItem", b =>
                {
                    b.HasOne("AlSsareea.Modules.Orders.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.OrderItemOption", b =>
                {
                    b.HasOne("AlSsareea.Modules.Orders.Domain.OrderItem", null)
                        .WithMany("Options")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_options_order_items_order_item_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.OrderStatusHistory", b =>
                {
                    b.HasOne("AlSsareea.Modules.Orders.Domain.Order", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_history_orders_order_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Infrastructure.Persistence.OrderCreationIdempotencyRecord", b =>
                {
                    b.HasOne("AlSsareea.Modules.Orders.Domain.Order", null)
                        .WithOne()
                        .HasForeignKey("AlSsareea.Modules.Orders.Infrastructure.Persistence.OrderCreationIdempotencyRecord", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_order_creation_idempotency_orders_order_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("AlSsareea.Modules.Orders.Domain.OrderItem", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
