<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\AlSsareea.BuildingBlocks.Application\AlSsareea.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\AlSsareea.Modules.Pricing.Contracts\AlSsareea.Modules.Pricing.Contracts.csproj" />
    <ProjectReference Include="..\AlSsareea.Modules.Pricing.Domain\AlSsareea.Modules.Pricing.Domain.csproj" />
  </ItemGroup>
</Project>
