// <auto-generated />
using System;
using AlSsareea.Modules.Tracking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Tracking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20260817162634_InitializeTrackingModule")]
    partial class InitializeTrackingModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tracking")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Tracking.Domain.DriverLatestLocation", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<double?>("HeadingDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("heading_degrees");

                    b.Property<long>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("position");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<double?>("SpeedMetersPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_meters_per_second");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DriverId")
                        .HasName("pk_driver_latest_locations");

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_driver_latest_locations_position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("RecordedAtUtc")
                        .HasDatabaseName("ix_driver_latest_locations_recorded_at_utc");

                    b.ToTable("driver_latest_locations", "tracking", t =>
                        {
                            t.HasCheckConstraint("ck_driver_latest_locations_position_srid", "ST_SRID(position) = 4326");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Tracking.Domain.DriverLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_meters");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<double?>("HeadingDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("heading_degrees");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("position");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<double?>("SpeedMetersPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_meters_per_second");

                    b.HasKey("Id")
                        .HasName("pk_driver_locations");

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_driver_locations_position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("ReceivedAtUtc")
                        .HasDatabaseName("ix_driver_locations_received_at_utc");

                    b.HasIndex("RecordedAtUtc")
                        .HasDatabaseName("ix_driver_locations_recorded_at_utc");

                    b.HasIndex("DriverId", "RecordedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_driver_locations_driver_id_recorded_at_utc");

                    b.HasIndex("DriverId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_driver_locations_driver_id_sequence_number");

                    b.ToTable("driver_locations", "tracking", t =>
                        {
                            t.HasCheckConstraint("ck_driver_locations_accuracy", "accuracy_meters > 0");

                            t.HasCheckConstraint("ck_driver_locations_heading", "heading_degrees IS NULL OR (heading_degrees >= 0 AND heading_degrees < 360)");

                            t.HasCheckConstraint("ck_driver_locations_position_srid", "ST_SRID(position) = 4326");

                            t.HasCheckConstraint("ck_driver_locations_sequence", "sequence_number >= 0");

                            t.HasCheckConstraint("ck_driver_locations_speed", "speed_meters_per_second IS NULL OR speed_meters_per_second >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
