// <auto-generated />
using System;
using System.Net;
using AlSsareea.Modules.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260721150008_InitializeIdentityDomain")]
    partial class InitializeIdentityDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("app_version");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_identifier");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("device_name");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("OperatingSystemVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operating_system_version");

                    b.Property<short>("Platform")
                        .HasColumnType("smallint")
                        .HasColumnName("platform");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_utc");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("ix_devices_is_revoked");

                    b.HasIndex("LastSeenUtc")
                        .HasDatabaseName("ix_devices_last_seen_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_user_id");

                    b.HasIndex("UserId", "DeviceIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_user_id_device_identifier");

                    b.ToTable("devices", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_devices_platform", "platform BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttemptedIdentifierHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("attempted_identifier_hash")
                        .IsFixedLength();

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<short?>("FailureReason")
                        .HasColumnType("smallint")
                        .HasColumnName("failure_reason");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("LoginSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_session_id");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_utc");

                    b.Property<short>("Result")
                        .HasColumnType("smallint")
                        .HasColumnName("result");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login_history");

                    b.HasIndex("AttemptedIdentifierHash")
                        .HasDatabaseName("ix_login_history_attempted_identifier_hash");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_login_history_device_id");

                    b.HasIndex("LoginSessionId")
                        .HasDatabaseName("ix_login_history_login_session_id");

                    b.HasIndex("OccurredUtc")
                        .HasDatabaseName("ix_login_history_occurred_utc");

                    b.HasIndex("Result")
                        .HasDatabaseName("ix_login_history_result");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_history_user_id");

                    b.HasIndex("UserId", "OccurredUtc")
                        .HasDatabaseName("ix_login_history_user_id_occurred_utc");

                    b.ToTable("login_history", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_login_history_consistency", "(result = 1 AND failure_reason IS NULL) OR (result = 2 AND failure_reason IS NOT NULL AND login_session_id IS NULL)");

                            t.HasCheckConstraint("ck_login_history_result", "result BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.LoginSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<short?>("EndReason")
                        .HasColumnType("smallint")
                        .HasColumnName("end_reason");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_utc");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_utc");

                    b.Property<Guid?>("RefreshTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_utc");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login_sessions");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_login_sessions_device_id");

                    b.HasIndex("ExpiresUtc")
                        .HasDatabaseName("ix_login_sessions_expires_utc");

                    b.HasIndex("LastActivityUtc")
                        .HasDatabaseName("ix_login_sessions_last_activity_utc");

                    b.HasIndex("RefreshTokenId")
                        .HasDatabaseName("ix_login_sessions_refresh_token_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_login_sessions_state");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_sessions_user_id");

                    b.ToTable("login_sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_login_sessions_activity", "last_activity_utc >= started_utc");

                            t.HasCheckConstraint("ck_login_sessions_end", "ended_utc IS NULL OR ended_utc >= started_utc");

                            t.HasCheckConstraint("ck_login_sessions_expiry", "expires_utc > started_utc");

                            t.HasCheckConstraint("ck_login_sessions_state", "state BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BecameActiveUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("became_active_utc");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("ReplacedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replaced_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_history_user_id");

                    b.HasIndex("UserId", "BecameActiveUtc")
                        .HasDatabaseName("ix_password_history_user_id_became_active_utc");

                    b.ToTable("password_history", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_password_history_replaced", "replaced_utc IS NULL OR replaced_utc >= became_active_utc");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_permissions_is_active");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_permissions_module");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_normalized_name");

                    b.ToTable("permissions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_permissions_name_format", "normalized_name = lower(normalized_name) AND normalized_name ~ '^[a-z0-9]+(\\.[a-z0-9]+){2,}$'");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_utc");

                    b.Property<IPAddress>("CreatedByIpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("created_by_ip_address");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<Guid>("LoginSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_session_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("revocation_reason");

                    b.Property<IPAddress>("RevokedByIpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("revoked_by_ip_address");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_utc");

                    b.Property<Guid>("SecurityStampSnapshot")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp_snapshot");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_refresh_tokens_device_id");

                    b.HasIndex("ExpiresUtc")
                        .HasDatabaseName("ix_refresh_tokens_expires_utc");

                    b.HasIndex("LoginSessionId")
                        .HasDatabaseName("ix_refresh_tokens_login_session_id");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("RevokedUtc")
                        .HasDatabaseName("ix_refresh_tokens_revoked_utc");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry", "expires_utc > created_utc");

                            t.HasCheckConstraint("ck_refresh_tokens_not_self_replaced", "replaced_by_token_id IS NULL OR replaced_by_token_id <> id");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_roles_is_active");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_normalized_name");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<DateTime>("AssignedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_utc");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_role_permissions_assigned_by_user_id");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime?>("DeletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTime>("LastPasswordChangedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_password_changed_utc");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_utc");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedPhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("normalized_phone_number");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<short>("UserType")
                        .HasColumnType("smallint")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_users_created_by_user_id");

                    b.HasIndex("CreatedUtc")
                        .HasDatabaseName("ix_users_created_utc");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("ix_users_deleted_by_user_id");

                    b.HasIndex("DeletedUtc")
                        .HasDatabaseName("ix_users_deleted_utc");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedPhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_phone_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_users_updated_by_user_id");

                    b.HasIndex("UserType")
                        .HasDatabaseName("ix_users_user_type");

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_users_contact_required", "normalized_email IS NOT NULL OR normalized_phone_number IS NOT NULL");

                            t.HasCheckConstraint("ck_users_status", "status BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_users_user_type", "user_type BETWEEN 1 AND 9");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<DateTime>("AssignedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_utc");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_user_roles_assigned_by_user_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.Device", b =>
                {
                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_devices_users_user_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.LoginHistory", b =>
                {
                    b.HasOne("AlSsareea.Modules.Identity.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_login_history_devices_device_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.LoginSession", null)
                        .WithMany()
                        .HasForeignKey("LoginSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_login_history_login_sessions_login_session_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_login_history_users_user_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.LoginSession", b =>
                {
                    b.HasOne("AlSsareea.Modules.Identity.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_login_sessions_devices_device_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("RefreshTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_login_sessions_refresh_tokens_refresh_token_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_login_sessions_users_user_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.PasswordHistory", b =>
                {
                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany("PasswordHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_history_users_user_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.RefreshToken", b =>
                {
                    b.HasOne("AlSsareea.Modules.Identity.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_devices_device_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.LoginSession", null)
                        .WithMany()
                        .HasForeignKey("LoginSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_login_sessions_login_session_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.RolePermission", b =>
                {
                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_role_permissions_users_assigned_by_user_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.User", b =>
                {
                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_created_by_user_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_deleted_by_user_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_updated_by_user_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.UserRole", b =>
                {
                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_roles_users_assigned_by_user_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("AlSsareea.Modules.Identity.Domain.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("AlSsareea.Modules.Identity.Domain.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("PasswordHistory");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
