using System;
using System.Net;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1861, IDE0161 // Generated by Entity Framework Core.

namespace AlSsareea.Modules.Identity.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitializeIdentityDomain : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "identity");

            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:postgis", ",,");

            migrationBuilder.CreateTable(
                name: "permissions",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    normalized_name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    display_name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    module = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    is_system = table.Column<bool>(type: "boolean", nullable: false),
                    is_active = table.Column<bool>(type: "boolean", nullable: false),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    concurrency_stamp = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_permissions", x => x.id);
                    table.CheckConstraint("ck_permissions_name_format", "normalized_name = lower(normalized_name) AND normalized_name ~ '^[a-z0-9]+(\\.[a-z0-9]+){2,}$'");
                });

            migrationBuilder.CreateTable(
                name: "roles",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    normalized_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    is_system = table.Column<bool>(type: "boolean", nullable: false),
                    is_active = table.Column<bool>(type: "boolean", nullable: false),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    concurrency_stamp = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_roles", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "users",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_type = table.Column<short>(type: "smallint", nullable: false),
                    status = table.Column<short>(type: "smallint", nullable: false),
                    email = table.Column<string>(type: "character varying(320)", maxLength: 320, nullable: true),
                    normalized_email = table.Column<string>(type: "character varying(320)", maxLength: 320, nullable: true),
                    phone_number = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: true),
                    normalized_phone_number = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: true),
                    password_hash = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false),
                    security_stamp = table.Column<Guid>(type: "uuid", nullable: false),
                    concurrency_stamp = table.Column<Guid>(type: "uuid", nullable: false),
                    failed_login_count = table.Column<int>(type: "integer", nullable: false),
                    lockout_end_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    last_password_changed_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    deleted_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    created_by_user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    updated_by_user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    deleted_by_user_id = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_users", x => x.id);
                    table.CheckConstraint("ck_users_contact_required", "normalized_email IS NOT NULL OR normalized_phone_number IS NOT NULL");
                    table.CheckConstraint("ck_users_status", "status BETWEEN 1 AND 6");
                    table.CheckConstraint("ck_users_user_type", "user_type BETWEEN 1 AND 9");
                    table.ForeignKey(
                        name: "fk_users_users_created_by_user_id",
                        column: x => x.created_by_user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_users_users_deleted_by_user_id",
                        column: x => x.deleted_by_user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_users_users_updated_by_user_id",
                        column: x => x.updated_by_user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "devices",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    device_identifier = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    platform = table.Column<short>(type: "smallint", nullable: false),
                    device_name = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: true),
                    app_version = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    operating_system_version = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    is_trusted = table.Column<bool>(type: "boolean", nullable: false),
                    is_revoked = table.Column<bool>(type: "boolean", nullable: false),
                    last_seen_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    revoked_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    concurrency_stamp = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_devices", x => x.id);
                    table.CheckConstraint("ck_devices_platform", "platform BETWEEN 1 AND 6");
                    table.ForeignKey(
                        name: "fk_devices_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "password_history",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    password_hash = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false),
                    became_active_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    replaced_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_password_history", x => x.id);
                    table.CheckConstraint("ck_password_history_replaced", "replaced_utc IS NULL OR replaced_utc >= became_active_utc");
                    table.ForeignKey(
                        name: "fk_password_history_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "role_permissions",
                schema: "identity",
                columns: table => new
                {
                    role_id = table.Column<Guid>(type: "uuid", nullable: false),
                    permission_id = table.Column<Guid>(type: "uuid", nullable: false),
                    assigned_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    assigned_by_user_id = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_role_permissions", x => new { x.role_id, x.permission_id });
                    table.ForeignKey(
                        name: "fk_role_permissions_permissions_permission_id",
                        column: x => x.permission_id,
                        principalSchema: "identity",
                        principalTable: "permissions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_role_permissions_roles_role_id",
                        column: x => x.role_id,
                        principalSchema: "identity",
                        principalTable: "roles",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_role_permissions_users_assigned_by_user_id",
                        column: x => x.assigned_by_user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "user_roles",
                schema: "identity",
                columns: table => new
                {
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    role_id = table.Column<Guid>(type: "uuid", nullable: false),
                    assigned_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    assigned_by_user_id = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_user_roles", x => new { x.user_id, x.role_id });
                    table.ForeignKey(
                        name: "fk_user_roles_roles_role_id",
                        column: x => x.role_id,
                        principalSchema: "identity",
                        principalTable: "roles",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_user_roles_users_assigned_by_user_id",
                        column: x => x.assigned_by_user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_user_roles_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "login_history",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    device_id = table.Column<Guid>(type: "uuid", nullable: true),
                    login_session_id = table.Column<Guid>(type: "uuid", nullable: true),
                    attempted_identifier_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                    result = table.Column<short>(type: "smallint", nullable: false),
                    failure_reason = table.Column<short>(type: "smallint", nullable: true),
                    ip_address = table.Column<IPAddress>(type: "inet", nullable: true),
                    user_agent = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    occurred_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    correlation_id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_login_history", x => x.id);
                    table.CheckConstraint("ck_login_history_consistency", "(result = 1 AND failure_reason IS NULL) OR (result = 2 AND failure_reason IS NOT NULL AND login_session_id IS NULL)");
                    table.CheckConstraint("ck_login_history_result", "result BETWEEN 1 AND 2");
                    table.ForeignKey(
                        name: "fk_login_history_devices_device_id",
                        column: x => x.device_id,
                        principalSchema: "identity",
                        principalTable: "devices",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_login_history_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "login_sessions",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    device_id = table.Column<Guid>(type: "uuid", nullable: true),
                    refresh_token_id = table.Column<Guid>(type: "uuid", nullable: true),
                    state = table.Column<short>(type: "smallint", nullable: false),
                    started_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    expires_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    last_activity_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    ended_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    end_reason = table.Column<short>(type: "smallint", nullable: true),
                    ip_address = table.Column<IPAddress>(type: "inet", nullable: true),
                    user_agent = table.Column<string>(type: "character varying(1024)", maxLength: 1024, nullable: true),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_login_sessions", x => x.id);
                    table.CheckConstraint("ck_login_sessions_activity", "last_activity_utc >= started_utc");
                    table.CheckConstraint("ck_login_sessions_end", "ended_utc IS NULL OR ended_utc >= started_utc");
                    table.CheckConstraint("ck_login_sessions_expiry", "expires_utc > started_utc");
                    table.CheckConstraint("ck_login_sessions_state", "state BETWEEN 1 AND 4");
                    table.ForeignKey(
                        name: "fk_login_sessions_devices_device_id",
                        column: x => x.device_id,
                        principalSchema: "identity",
                        principalTable: "devices",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_login_sessions_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "refresh_tokens",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    device_id = table.Column<Guid>(type: "uuid", nullable: true),
                    login_session_id = table.Column<Guid>(type: "uuid", nullable: false),
                    token_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                    security_stamp_snapshot = table.Column<Guid>(type: "uuid", nullable: false),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    expires_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    consumed_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    revoked_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    revocation_reason = table.Column<string>(type: "character varying(250)", maxLength: 250, nullable: true),
                    replaced_by_token_id = table.Column<Guid>(type: "uuid", nullable: true),
                    created_by_ip_address = table.Column<IPAddress>(type: "inet", nullable: true),
                    revoked_by_ip_address = table.Column<IPAddress>(type: "inet", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_refresh_tokens", x => x.id);
                    table.CheckConstraint("ck_refresh_tokens_expiry", "expires_utc > created_utc");
                    table.CheckConstraint("ck_refresh_tokens_not_self_replaced", "replaced_by_token_id IS NULL OR replaced_by_token_id <> id");
                    table.ForeignKey(
                        name: "fk_refresh_tokens_devices_device_id",
                        column: x => x.device_id,
                        principalSchema: "identity",
                        principalTable: "devices",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_refresh_tokens_login_sessions_login_session_id",
                        column: x => x.login_session_id,
                        principalSchema: "identity",
                        principalTable: "login_sessions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_refresh_tokens_refresh_tokens_replaced_by_token_id",
                        column: x => x.replaced_by_token_id,
                        principalSchema: "identity",
                        principalTable: "refresh_tokens",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_refresh_tokens_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_devices_is_revoked",
                schema: "identity",
                table: "devices",
                column: "is_revoked");

            migrationBuilder.CreateIndex(
                name: "ix_devices_last_seen_utc",
                schema: "identity",
                table: "devices",
                column: "last_seen_utc");

            migrationBuilder.CreateIndex(
                name: "ix_devices_user_id",
                schema: "identity",
                table: "devices",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ux_devices_user_id_device_identifier",
                schema: "identity",
                table: "devices",
                columns: new[] { "user_id", "device_identifier" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_login_history_attempted_identifier_hash",
                schema: "identity",
                table: "login_history",
                column: "attempted_identifier_hash");

            migrationBuilder.CreateIndex(
                name: "ix_login_history_device_id",
                schema: "identity",
                table: "login_history",
                column: "device_id");

            migrationBuilder.CreateIndex(
                name: "ix_login_history_login_session_id",
                schema: "identity",
                table: "login_history",
                column: "login_session_id");

            migrationBuilder.CreateIndex(
                name: "ix_login_history_occurred_utc",
                schema: "identity",
                table: "login_history",
                column: "occurred_utc");

            migrationBuilder.CreateIndex(
                name: "ix_login_history_result",
                schema: "identity",
                table: "login_history",
                column: "result");

            migrationBuilder.CreateIndex(
                name: "ix_login_history_user_id",
                schema: "identity",
                table: "login_history",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_login_history_user_id_occurred_utc",
                schema: "identity",
                table: "login_history",
                columns: new[] { "user_id", "occurred_utc" });

            migrationBuilder.CreateIndex(
                name: "ix_login_sessions_device_id",
                schema: "identity",
                table: "login_sessions",
                column: "device_id");

            migrationBuilder.CreateIndex(
                name: "ix_login_sessions_expires_utc",
                schema: "identity",
                table: "login_sessions",
                column: "expires_utc");

            migrationBuilder.CreateIndex(
                name: "ix_login_sessions_last_activity_utc",
                schema: "identity",
                table: "login_sessions",
                column: "last_activity_utc");

            migrationBuilder.CreateIndex(
                name: "ix_login_sessions_refresh_token_id",
                schema: "identity",
                table: "login_sessions",
                column: "refresh_token_id");

            migrationBuilder.CreateIndex(
                name: "ix_login_sessions_state",
                schema: "identity",
                table: "login_sessions",
                column: "state");

            migrationBuilder.CreateIndex(
                name: "ix_login_sessions_user_id",
                schema: "identity",
                table: "login_sessions",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_password_history_user_id",
                schema: "identity",
                table: "password_history",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_password_history_user_id_became_active_utc",
                schema: "identity",
                table: "password_history",
                columns: new[] { "user_id", "became_active_utc" });

            migrationBuilder.CreateIndex(
                name: "ix_permissions_is_active",
                schema: "identity",
                table: "permissions",
                column: "is_active");

            migrationBuilder.CreateIndex(
                name: "ix_permissions_module",
                schema: "identity",
                table: "permissions",
                column: "module");

            migrationBuilder.CreateIndex(
                name: "ux_permissions_normalized_name",
                schema: "identity",
                table: "permissions",
                column: "normalized_name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_refresh_tokens_device_id",
                schema: "identity",
                table: "refresh_tokens",
                column: "device_id");

            migrationBuilder.CreateIndex(
                name: "ix_refresh_tokens_expires_utc",
                schema: "identity",
                table: "refresh_tokens",
                column: "expires_utc");

            migrationBuilder.CreateIndex(
                name: "ix_refresh_tokens_login_session_id",
                schema: "identity",
                table: "refresh_tokens",
                column: "login_session_id");

            migrationBuilder.CreateIndex(
                name: "ix_refresh_tokens_replaced_by_token_id",
                schema: "identity",
                table: "refresh_tokens",
                column: "replaced_by_token_id");

            migrationBuilder.CreateIndex(
                name: "ix_refresh_tokens_revoked_utc",
                schema: "identity",
                table: "refresh_tokens",
                column: "revoked_utc");

            migrationBuilder.CreateIndex(
                name: "ix_refresh_tokens_user_id",
                schema: "identity",
                table: "refresh_tokens",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ux_refresh_tokens_token_hash",
                schema: "identity",
                table: "refresh_tokens",
                column: "token_hash",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_role_permissions_assigned_by_user_id",
                schema: "identity",
                table: "role_permissions",
                column: "assigned_by_user_id");

            migrationBuilder.CreateIndex(
                name: "ix_role_permissions_permission_id",
                schema: "identity",
                table: "role_permissions",
                column: "permission_id");

            migrationBuilder.CreateIndex(
                name: "ix_roles_is_active",
                schema: "identity",
                table: "roles",
                column: "is_active");

            migrationBuilder.CreateIndex(
                name: "ux_roles_normalized_name",
                schema: "identity",
                table: "roles",
                column: "normalized_name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_user_roles_assigned_by_user_id",
                schema: "identity",
                table: "user_roles",
                column: "assigned_by_user_id");

            migrationBuilder.CreateIndex(
                name: "ix_user_roles_role_id",
                schema: "identity",
                table: "user_roles",
                column: "role_id");

            migrationBuilder.CreateIndex(
                name: "ix_users_created_by_user_id",
                schema: "identity",
                table: "users",
                column: "created_by_user_id");

            migrationBuilder.CreateIndex(
                name: "ix_users_created_utc",
                schema: "identity",
                table: "users",
                column: "created_utc");

            migrationBuilder.CreateIndex(
                name: "ix_users_deleted_by_user_id",
                schema: "identity",
                table: "users",
                column: "deleted_by_user_id");

            migrationBuilder.CreateIndex(
                name: "ix_users_deleted_utc",
                schema: "identity",
                table: "users",
                column: "deleted_utc");

            migrationBuilder.CreateIndex(
                name: "ix_users_status",
                schema: "identity",
                table: "users",
                column: "status");

            migrationBuilder.CreateIndex(
                name: "ix_users_updated_by_user_id",
                schema: "identity",
                table: "users",
                column: "updated_by_user_id");

            migrationBuilder.CreateIndex(
                name: "ix_users_user_type",
                schema: "identity",
                table: "users",
                column: "user_type");

            migrationBuilder.CreateIndex(
                name: "ux_users_normalized_email",
                schema: "identity",
                table: "users",
                column: "normalized_email",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ux_users_normalized_phone_number",
                schema: "identity",
                table: "users",
                column: "normalized_phone_number",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_login_history_login_sessions_login_session_id",
                schema: "identity",
                table: "login_history",
                column: "login_session_id",
                principalSchema: "identity",
                principalTable: "login_sessions",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "fk_login_sessions_refresh_tokens_refresh_token_id",
                schema: "identity",
                table: "login_sessions",
                column: "refresh_token_id",
                principalSchema: "identity",
                principalTable: "refresh_tokens",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_devices_users_user_id",
                schema: "identity",
                table: "devices");

            migrationBuilder.DropForeignKey(
                name: "fk_login_sessions_users_user_id",
                schema: "identity",
                table: "login_sessions");

            migrationBuilder.DropForeignKey(
                name: "fk_refresh_tokens_users_user_id",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.DropForeignKey(
                name: "fk_login_sessions_devices_device_id",
                schema: "identity",
                table: "login_sessions");

            migrationBuilder.DropForeignKey(
                name: "fk_refresh_tokens_devices_device_id",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.DropForeignKey(
                name: "fk_refresh_tokens_login_sessions_login_session_id",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.DropTable(
                name: "login_history",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "password_history",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "role_permissions",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "user_roles",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "permissions",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "roles",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "users",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "devices",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "login_sessions",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "refresh_tokens",
                schema: "identity");
        }
    }
}
