using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1861, IDE0161 // Generated by Entity Framework Core.

namespace AlSsareea.Modules.Identity.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddAuthenticationAndAuthorization : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "family_id",
                schema: "identity",
                table: "refresh_tokens",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "replay_detected_utc",
                schema: "identity",
                table: "refresh_tokens",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "idempotency_records",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    owner_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    operation = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    key_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                    request_fingerprint = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                    resource_id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    expires_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_idempotency_records", x => x.id);
                    table.CheckConstraint("ck_idempotency_records_expiry", "expires_utc > created_utc");
                });

            migrationBuilder.CreateTable(
                name: "otp_challenges",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    destination_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                    purpose = table.Column<short>(type: "smallint", nullable: false),
                    code_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                    failed_attempts = table.Column<int>(type: "integer", nullable: false),
                    maximum_attempts = table.Column<int>(type: "integer", nullable: false),
                    created_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    expires_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    next_resend_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    used_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    device_identifier_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                    ip_address_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_otp_challenges", x => x.id);
                    table.CheckConstraint("ck_otp_challenges_attempts", "failed_attempts >= 0 AND failed_attempts <= maximum_attempts AND maximum_attempts > 0");
                    table.CheckConstraint("ck_otp_challenges_dates", "expires_utc > created_utc AND next_resend_utc > created_utc");
                    table.CheckConstraint("ck_otp_challenges_purpose", "purpose BETWEEN 1 AND 4");
                });

            migrationBuilder.CreateTable(
                name: "security_audit",
                schema: "identity",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    event_type = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    session_id = table.Column<Guid>(type: "uuid", nullable: true),
                    device_id = table.Column<Guid>(type: "uuid", nullable: true),
                    occurred_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    correlation_id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    ip_address = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    user_agent = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: true),
                    result_category = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_security_audit", x => x.id);
                    table.ForeignKey(
                        name: "fk_security_audit_devices_device_id",
                        column: x => x.device_id,
                        principalSchema: "identity",
                        principalTable: "devices",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_security_audit_login_sessions_session_id",
                        column: x => x.session_id,
                        principalSchema: "identity",
                        principalTable: "login_sessions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_security_audit_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "identity",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_refresh_tokens_family_id",
                schema: "identity",
                table: "refresh_tokens",
                column: "family_id");

            migrationBuilder.CreateIndex(
                name: "ix_idempotency_records_expires_utc",
                schema: "identity",
                table: "idempotency_records",
                column: "expires_utc");

            migrationBuilder.CreateIndex(
                name: "ux_idempotency_records_owner_operation_key_hash",
                schema: "identity",
                table: "idempotency_records",
                columns: new[] { "owner_key", "operation", "key_hash" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_otp_challenges_destination_hash_purpose",
                schema: "identity",
                table: "otp_challenges",
                columns: new[] { "destination_hash", "purpose" });

            migrationBuilder.CreateIndex(
                name: "ix_otp_challenges_expires_utc",
                schema: "identity",
                table: "otp_challenges",
                column: "expires_utc");

            migrationBuilder.CreateIndex(
                name: "ix_security_audit_device_id",
                schema: "identity",
                table: "security_audit",
                column: "device_id");

            migrationBuilder.CreateIndex(
                name: "ix_security_audit_event_type",
                schema: "identity",
                table: "security_audit",
                column: "event_type");

            migrationBuilder.CreateIndex(
                name: "ix_security_audit_session_id",
                schema: "identity",
                table: "security_audit",
                column: "session_id");

            migrationBuilder.CreateIndex(
                name: "ix_security_audit_user_id_occurred_utc",
                schema: "identity",
                table: "security_audit",
                columns: new[] { "user_id", "occurred_utc" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "idempotency_records",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "otp_challenges",
                schema: "identity");

            migrationBuilder.DropTable(
                name: "security_audit",
                schema: "identity");

            migrationBuilder.DropIndex(
                name: "ix_refresh_tokens_family_id",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.DropColumn(
                name: "family_id",
                schema: "identity",
                table: "refresh_tokens");

            migrationBuilder.DropColumn(
                name: "replay_detected_utc",
                schema: "identity",
                table: "refresh_tokens");
        }
    }
}
