// <auto-generated />
using System;
using AlSsareea.Modules.Drivers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Drivers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DriversDbContext))]
    partial class DriversDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("drivers")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<short>("ActivationStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("activation_status");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<short>("AvailabilityStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("availability_status");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentLoad")
                        .HasColumnType("integer")
                        .HasColumnName("current_load");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<short>("EmploymentType")
                        .HasColumnType("smallint")
                        .HasColumnName("employment_type");

                    b.Property<DateTime>("LastAvailabilityChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_availability_changed_at_utc");

                    b.Property<int>("MaximumConcurrentDeliveries")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_concurrent_deliveries");

                    b.Property<Guid?>("ProfilePhotoMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_photo_media_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_drivers");

                    b.HasIndex("ActivationStatus")
                        .HasDatabaseName("ix_drivers_activation_status");

                    b.HasIndex("AvailabilityStatus")
                        .HasDatabaseName("ix_drivers_availability_status");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_drivers_created_at_utc");

                    b.HasIndex("EmploymentType")
                        .HasDatabaseName("ix_drivers_employment_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_drivers_status");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("ix_drivers_updated_at_utc");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_drivers_user_id");

                    b.ToTable("drivers", "drivers", t =>
                        {
                            t.HasCheckConstraint("ck_drivers_activation_status", "activation_status BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_drivers_availability_status", "availability_status BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_drivers_capacity", "maximum_concurrent_deliveries > 0 AND current_load >= 0 AND current_load <= maximum_concurrent_deliveries");

                            t.HasCheckConstraint("ck_drivers_status", "status BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_driver_documents");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_documents_driver_id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_driver_documents_expires_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_driver_documents_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_driver_documents_type");

                    b.HasIndex("DriverId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_documents_current_type")
                        .HasFilter("status IN (1, 2)");

                    b.ToTable("driver_documents", "drivers", t =>
                        {
                            t.HasCheckConstraint("ck_driver_documents_dates", "expires_at_utc IS NULL OR issued_at_utc IS NULL OR expires_at_utc > issued_at_utc");

                            t.HasCheckConstraint("ck_driver_documents_rejection", "status <> 3 OR rejection_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_driver_documents_review", "status NOT IN (2, 3) OR reviewed_at_utc IS NOT NULL");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverShift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_utc");

                    b.Property<DateTime?>("ActualStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_utc");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_utc");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_utc");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_driver_shifts");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_shifts_driver_id");

                    b.HasIndex("ScheduledStartUtc")
                        .HasDatabaseName("ix_driver_shifts_scheduled_start_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_driver_shifts_status");

                    b.ToTable("driver_shifts", "drivers", t =>
                        {
                            t.HasCheckConstraint("ck_driver_shifts_actual", "actual_end_utc IS NULL OR actual_start_utc IS NOT NULL AND actual_end_utc >= actual_start_utc");

                            t.HasCheckConstraint("ck_driver_shifts_scheduled", "scheduled_end_utc > scheduled_start_utc");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverSuspension", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("LiftReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lift_reason");

                    b.Property<DateTime?>("LiftedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lifted_at_utc");

                    b.Property<Guid?>("LiftedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("lifted_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason_code");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_driver_suspensions");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_suspensions_driver_id");

                    b.HasIndex("EndsAtUtc")
                        .HasDatabaseName("ix_driver_suspensions_ends_at_utc");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_driver_suspensions_starts_at_utc");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_driver_suspensions_status");

                    b.ToTable("driver_suspensions", "drivers", t =>
                        {
                            t.HasCheckConstraint("ck_driver_suspensions_dates", "ends_at_utc IS NULL OR ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverViolation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint")
                        .HasColumnName("severity");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("violation_type");

                    b.HasKey("Id")
                        .HasName("pk_driver_violations");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_violations_driver_id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_driver_violations_occurred_at_utc");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_driver_violations_severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_driver_violations_status");

                    b.ToTable("driver_violations", "drivers");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverZoneAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at_utc");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_driver_zone_assignments");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_zones_primary")
                        .HasFilter("is_active AND is_primary");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_driver_zones_zone_id");

                    b.HasIndex("DriverId", "ZoneId")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_zones_active")
                        .HasFilter("is_active");

                    b.ToTable("driver_zone_assignments", "drivers");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("NormalizedPlateNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_plate_number");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate_number");

                    b.Property<string>("RegistrationCountry")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("registration_country")
                        .IsFixedLength();

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_driver_primary_active")
                        .HasFilter("is_primary AND status = 2");

                    b.HasIndex("NormalizedPlateNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_active_plate")
                        .HasFilter("normalized_plate_number IS NOT NULL AND status <> 6");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_vehicles_status");

                    b.ToTable("vehicles", "drivers", t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_status", "status BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_vehicles_type", "type BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_vehicles_year", "year IS NULL OR year BETWEEN 1980 AND 2100");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Infrastructure.Persistence.DriverAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason_code");

                    b.HasKey("Id")
                        .HasName("pk_driver_audit");

                    b.HasIndex("DriverId", "OccurredAtUtc")
                        .HasDatabaseName("ix_driver_audit_driver_occurred");

                    b.ToTable("audit_records", "drivers");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Infrastructure.Persistence.DriverIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("key_hash")
                        .IsFixedLength();

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash")
                        .IsFixedLength();

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<short?>("ResponseStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("response_status");

                    b.HasKey("Id")
                        .HasName("pk_driver_idempotency");

                    b.HasIndex("ActorUserId", "Operation", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_idempotency_scope");

                    b.ToTable("idempotency_records", "drivers", t =>
                        {
                            t.HasCheckConstraint("ck_driver_idempotency_hashes", "char_length(key_hash) = 64 AND char_length(request_hash) = 64");

                            t.HasCheckConstraint("ck_driver_idempotency_response", "response_json IS NULL OR jsonb_typeof(response_json) = 'object'");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Infrastructure.Persistence.DriverOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_driver_outbox");

                    b.HasIndex("ProcessedAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_driver_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", "drivers", t =>
                        {
                            t.HasCheckConstraint("ck_driver_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_driver_outbox_event_type", "char_length(event_type) > 0");

                            t.HasCheckConstraint("ck_driver_outbox_payload", "jsonb_typeof(payload) = 'object'");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverDocument", b =>
                {
                    b.HasOne("AlSsareea.Modules.Drivers.Domain.Driver", null)
                        .WithMany("Documents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_driver_documents_drivers_driver_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverShift", b =>
                {
                    b.HasOne("AlSsareea.Modules.Drivers.Domain.Driver", null)
                        .WithMany("Shifts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_driver_shifts_drivers_driver_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverSuspension", b =>
                {
                    b.HasOne("AlSsareea.Modules.Drivers.Domain.Driver", null)
                        .WithMany("Suspensions")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_driver_suspensions_drivers_driver_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverViolation", b =>
                {
                    b.HasOne("AlSsareea.Modules.Drivers.Domain.Driver", null)
                        .WithMany("Violations")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_driver_violations_drivers_driver_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.DriverZoneAssignment", b =>
                {
                    b.HasOne("AlSsareea.Modules.Drivers.Domain.Driver", null)
                        .WithMany("ZoneAssignments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_driver_zones_drivers_driver_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.Vehicle", b =>
                {
                    b.HasOne("AlSsareea.Modules.Drivers.Domain.Driver", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_drivers_driver_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Drivers.Domain.Driver", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Shifts");

                    b.Navigation("Suspensions");

                    b.Navigation("Vehicles");

                    b.Navigation("Violations");

                    b.Navigation("ZoneAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
