// <auto-generated />
using System;
using AlSsareea.Modules.Dispatching.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Dispatching.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DispatchingDbContext))]
    partial class DispatchingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dispatching")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Domain.DispatchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentLoad")
                        .HasColumnType("integer")
                        .HasColumnName("current_load");

                    b.Property<Guid>("DispatchRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_request_id");

                    b.Property<long>("DistanceMeters")
                        .HasColumnType("bigint")
                        .HasColumnName("distance_meters");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<int>("EtaSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("eta_seconds");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("explanation");

                    b.Property<DateTime?>("LastAssignmentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_assignment_at_utc");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_capacity");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_dispatch_candidates");

                    b.HasIndex("DispatchRequestId", "AttemptNumber", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatch_candidates_request_attempt_driver");

                    b.HasIndex("DispatchRequestId", "AttemptNumber", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatch_candidates_request_attempt_rank");

                    b.ToTable("dispatch_candidates", "dispatching", t =>
                        {
                            t.HasCheckConstraint("ck_dispatch_candidates_metrics", "distance_meters >= 0 AND eta_seconds >= 0 AND current_load >= 0 AND maximum_capacity > 0");

                            t.HasCheckConstraint("ck_dispatch_candidates_rank", "rank > 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Domain.DispatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<Guid>("DispatchRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_request_id");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_dispatch_history");

                    b.HasIndex("DispatchRequestId", "OccurredAtUtc")
                        .HasDatabaseName("ix_dispatch_history_request_occurred");

                    b.ToTable("dispatch_history", "dispatching");
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Domain.DispatchOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decline_reason");

                    b.Property<Guid>("DispatchRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_request_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("OfferedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at_utc");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at_utc");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_dispatch_offers");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_dispatch_offers_active_expiry")
                        .HasFilter("status = 1");

                    b.HasIndex("DispatchRequestId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatch_offers_request_sequence");

                    b.HasIndex("DispatchRequestId", "AttemptNumber", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatch_offers_request_attempt_driver");

                    b.ToTable("dispatch_offers", "dispatching", t =>
                        {
                            t.HasCheckConstraint("ck_dispatch_offers_expiry", "expires_at_utc > offered_at_utc");

                            t.HasCheckConstraint("ck_dispatch_offers_response", "status = 1 AND responded_at_utc IS NULL OR status <> 1 AND responded_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_dispatch_offers_status", "status BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Domain.DispatchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_driver_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid?>("MerchantBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_branch_id");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_latitude");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_longitude");

                    b.Property<int?>("PreparationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("preparation_seconds");

                    b.Property<short?>("RequiredVehicleType")
                        .HasColumnType("smallint")
                        .HasColumnName("required_vehicle_type");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_dispatch_requests");

                    b.HasIndex("AssignedDriverId")
                        .HasDatabaseName("ix_dispatch_requests_assigned_driver_id");

                    b.HasIndex("DeliveryId")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatch_requests_delivery_id");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_dispatch_requests_status_updated");

                    b.ToTable("dispatch_requests", "dispatching", t =>
                        {
                            t.HasCheckConstraint("ck_dispatch_requests_assignment", "status <> 4 OR assigned_driver_id IS NOT NULL AND completed_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_dispatch_requests_attempt", "attempt_number >= 0");

                            t.HasCheckConstraint("ck_dispatch_requests_coordinates", "pickup_latitude BETWEEN -90 AND 90 AND pickup_longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_dispatch_requests_status", "status BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Infrastructure.Persistence.DispatchAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DispatchRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_request_id");

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key_hash");

                    b.Property<short>("NewStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("new_status");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<short>("OldStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("old_status");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_dispatch_audit");

                    b.HasIndex("DispatchRequestId", "OccurredAtUtc")
                        .HasDatabaseName("ix_dispatch_audit_request_occurred");

                    b.ToTable("dispatch_audit", "dispatching", t =>
                        {
                            t.HasCheckConstraint("ck_dispatch_audit_key_hash", "char_length(idempotency_key_hash) = 64");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Infrastructure.Persistence.DispatchIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DispatchRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_request_id");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.HasKey("Id")
                        .HasName("pk_dispatch_idempotency_records");

                    b.HasIndex("ActorId", "Operation", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatch_idempotency_actor_operation_key");

                    b.ToTable("dispatch_idempotency_records", "dispatching", t =>
                        {
                            t.HasCheckConstraint("ck_dispatch_idempotency_hashes", "char_length(key_hash) = 64 AND char_length(request_hash) = 64");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Infrastructure.Persistence.DispatchOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_dispatch_outbox_messages");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_dispatch_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("dispatch_outbox_messages", "dispatching", t =>
                        {
                            t.HasCheckConstraint("ck_dispatch_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_dispatch_outbox_payload", "jsonb_typeof(payload) = 'object'");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Domain.DispatchCandidate", b =>
                {
                    b.HasOne("AlSsareea.Modules.Dispatching.Domain.DispatchRequest", null)
                        .WithMany("Candidates")
                        .HasForeignKey("DispatchRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_dispatch_candidates_dispatch_requests_dispatch_request_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Domain.DispatchHistory", b =>
                {
                    b.HasOne("AlSsareea.Modules.Dispatching.Domain.DispatchRequest", null)
                        .WithMany("History")
                        .HasForeignKey("DispatchRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_dispatch_history_dispatch_requests_dispatch_request_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Domain.DispatchOffer", b =>
                {
                    b.HasOne("AlSsareea.Modules.Dispatching.Domain.DispatchRequest", null)
                        .WithMany("Offers")
                        .HasForeignKey("DispatchRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_dispatch_offers_dispatch_requests_dispatch_request_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Dispatching.Domain.DispatchRequest", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("History");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
