<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AlSsareea.Modules.Tracking.Application\AlSsareea.Modules.Tracking.Application.csproj" />
    <ProjectReference Include="..\AlSsareea.Modules.Tracking.Domain\AlSsareea.Modules.Tracking.Domain.csproj" />
    <ProjectReference Include="..\AlSsareea.Modules.Tracking.Contracts\AlSsareea.Modules.Tracking.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\AlSsareea.BuildingBlocks.Application\AlSsareea.BuildingBlocks.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>
</Project>
