using AlSsareea.Modules.Catalog.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AlSsareea.Modules.Catalog.Infrastructure.Persistence;

internal static class CatalogConfigurationExtensions
{
    internal static PropertyBuilder<T> Id<T>(this PropertyBuilder<T> p, Func<T, Guid> to, Func<Guid, T> from) where T : struct => p.HasConversion(x => to(x), x => from(x)).HasColumnType("uuid").ValueGeneratedNever();
    internal static PropertyBuilder<DateTime> Utc(this PropertyBuilder<DateTime> p) => p.HasColumnType("timestamp with time zone"); internal static PropertyBuilder<DateTime?> Utc(this PropertyBuilder<DateTime?> p) => p.HasColumnType("timestamp with time zone");
}
internal sealed class CatalogConfiguration : IEntityTypeConfiguration<Catalog.Domain.Catalog>
{
    public void Configure(EntityTypeBuilder<Catalog.Domain.Catalog> b) { b.ToTable("catalogs", CatalogPersistence.Schema, t => t.HasCheckConstraint("ck_catalogs_status", "status BETWEEN 1 AND 4")); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new CatalogId(x)); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.HasIndex(x => x.MerchantId).IsUnique(); b.Property(x => x.Name).HasMaxLength(200); b.Property(x => x.Description).HasMaxLength(2000); b.Property(x => x.DefaultLanguage).HasMaxLength(2); b.Property(x => x.Status).HasConversion<short>(); b.Property(x => x.CreatedAtUtc).Utc(); b.Property(x => x.UpdatedAtUtc).Utc(); b.Property(x => x.ConcurrencyStamp).IsConcurrencyToken(); b.Ignore(x => x.DomainEvents); }
}
internal sealed class CategoryConfiguration : IEntityTypeConfiguration<Category>
{
    public void Configure(EntityTypeBuilder<Category> b) { b.ToTable("categories", CatalogPersistence.Schema, t => t.HasCheckConstraint("ck_categories_sort_order", "sort_order >= 0")); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new CategoryId(x)); b.Property(x => x.CatalogId).Id(x => x.Value, x => new CatalogId(x)); b.Property(x => x.ParentCategoryId).HasConversion(x => x.HasValue ? x.Value.Value : (Guid?)null, x => x.HasValue ? new CategoryId(x.Value) : null); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.Property(x => x.CreatedAtUtc).Utc(); b.Property(x => x.UpdatedAtUtc).Utc(); b.Property(x => x.ConcurrencyStamp).IsConcurrencyToken(); b.HasIndex(x => new { x.MerchantId, x.CatalogId, x.SortOrder }); b.HasOne<Category>().WithMany().HasForeignKey(x => x.ParentCategoryId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.Translations).WithOne().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict); b.Ignore(x => x.DomainEvents); }
}
internal sealed class CategoryTranslationConfiguration : IEntityTypeConfiguration<CategoryTranslation> { public void Configure(EntityTypeBuilder<CategoryTranslation> b) { b.ToTable("category_translations"); b.HasKey(x => new { x.CategoryId, x.LanguageCode }); b.Property(x => x.CategoryId).Id(x => x.Value, x => new CategoryId(x)); b.Property(x => x.LanguageCode).HasMaxLength(2); b.Property(x => x.Name).HasMaxLength(200); b.Property(x => x.Description).HasMaxLength(2000); b.Property(x => x.SearchText).HasMaxLength(2200); b.HasIndex(x => x.SearchText); } }
internal sealed class MenuSectionConfiguration : IEntityTypeConfiguration<MenuSection> { public void Configure(EntityTypeBuilder<MenuSection> b) { b.ToTable("menu_sections", CatalogPersistence.Schema, t => t.HasCheckConstraint("ck_menu_sections_sort_order", "sort_order >= 0")); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new MenuSectionId(x)); b.Property(x => x.CatalogId).Id(x => x.Value, x => new CatalogId(x)); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.Property(x => x.AvailableFromUtc).Utc(); b.Property(x => x.AvailableUntilUtc).Utc(); b.Property(x => x.CreatedAtUtc).Utc(); b.Property(x => x.UpdatedAtUtc).Utc(); b.Property(x => x.ConcurrencyStamp).IsConcurrencyToken(); b.HasMany(x => x.Translations).WithOne().HasForeignKey(x => x.MenuSectionId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.Products).WithOne().HasForeignKey(x => x.MenuSectionId).OnDelete(DeleteBehavior.Restrict); b.Ignore(x => x.DomainEvents); } }
internal sealed class MenuSectionTranslationConfiguration : IEntityTypeConfiguration<MenuSectionTranslation> { public void Configure(EntityTypeBuilder<MenuSectionTranslation> b) { b.ToTable("menu_section_translations"); b.HasKey(x => new { x.MenuSectionId, x.LanguageCode }); b.Property(x => x.MenuSectionId).Id(x => x.Value, x => new MenuSectionId(x)); b.Property(x => x.LanguageCode).HasMaxLength(2); b.Property(x => x.Name).HasMaxLength(200); b.Property(x => x.Description).HasMaxLength(2000); } }
internal sealed class MenuSectionProductConfiguration : IEntityTypeConfiguration<MenuSectionProduct> { public void Configure(EntityTypeBuilder<MenuSectionProduct> b) { b.ToTable("menu_section_products", CatalogPersistence.Schema, t => t.HasCheckConstraint("ck_menu_section_products_sort_order", "sort_order >= 0")); b.HasKey(x => new { x.MenuSectionId, x.ProductId }); b.Property(x => x.MenuSectionId).Id(x => x.Value, x => new MenuSectionId(x)); b.Property(x => x.ProductId).Id(x => x.Value, x => new ProductId(x)); } }
internal sealed class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> b) { b.ToTable("products", CatalogPersistence.Schema, t => { t.HasCheckConstraint("ck_products_price", "base_price_minor >= 0"); t.HasCheckConstraint("ck_products_sort", "sort_order >= 0"); t.HasCheckConstraint("ck_products_version", "current_version >= 1"); }); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new ProductId(x)); b.Property(x => x.CatalogId).Id(x => x.Value, x => new CatalogId(x)); b.Property(x => x.CategoryId).HasConversion(x => x.HasValue ? x.Value.Value : (Guid?)null, x => x.HasValue ? new CategoryId(x.Value) : null); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.Property(x => x.Sku).HasMaxLength(100); b.Property(x => x.Currency).HasMaxLength(3); b.Property(x => x.TaxCategoryReference).HasMaxLength(100); b.Property(x => x.Status).HasConversion<short>(); b.Property(x => x.InventoryStatus).HasConversion<short>(); b.Property(x => x.CreatedAtUtc).Utc(); b.Property(x => x.UpdatedAtUtc).Utc(); b.Property(x => x.PublishedAtUtc).Utc(); b.Property(x => x.ConcurrencyStamp).IsConcurrencyToken(); b.HasIndex(x => new { x.MerchantId, x.Sku }).IsUnique().HasFilter("sku IS NOT NULL"); b.HasIndex(x => new { x.MerchantId, x.Status, x.InventoryStatus, x.IsVisible, x.SortOrder }); b.HasMany(x => x.Translations).WithOne().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.Variants).WithOne().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.OptionGroups).WithOne().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.Images).WithOne().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.Availability).WithOne().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict); b.Ignore(x => x.DomainEvents); }
}
internal sealed class ProductTranslationConfiguration : IEntityTypeConfiguration<ProductTranslation> { public void Configure(EntityTypeBuilder<ProductTranslation> b) { b.ToTable("product_translations"); b.HasKey(x => new { x.ProductId, x.LanguageCode }); b.Property(x => x.ProductId).Id(x => x.Value, x => new ProductId(x)); b.Property(x => x.LanguageCode).HasMaxLength(2); b.Property(x => x.Name).HasMaxLength(200); b.Property(x => x.Description).HasMaxLength(4000); b.Property(x => x.SearchText).HasMaxLength(4200); b.HasIndex(x => x.SearchText); } }
internal sealed class ProductVariantConfiguration : IEntityTypeConfiguration<ProductVariant> { public void Configure(EntityTypeBuilder<ProductVariant> b) { b.ToTable("product_variants", CatalogPersistence.Schema, t => t.HasCheckConstraint("ck_product_variants_sort", "sort_order >= 0")); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new ProductVariantId(x)); b.Property(x => x.ProductId).Id(x => x.Value, x => new ProductId(x)); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.Property(x => x.Sku).HasMaxLength(100); b.Property(x => x.InventoryStatus).HasConversion<short>(); b.Property(x => x.CreatedAtUtc).Utc(); b.Property(x => x.UpdatedAtUtc).Utc(); b.Property(x => x.ConcurrencyStamp).IsConcurrencyToken(); b.HasIndex(x => new { x.MerchantId, x.Sku }).IsUnique().HasFilter("sku IS NOT NULL"); b.HasIndex(x => x.ProductId).IsUnique().HasFilter("is_default = true"); b.HasMany(x => x.Translations).WithOne().HasForeignKey(x => x.ProductVariantId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class ProductVariantTranslationConfiguration : IEntityTypeConfiguration<ProductVariantTranslation> { public void Configure(EntityTypeBuilder<ProductVariantTranslation> b) { b.ToTable("product_variant_translations"); b.HasKey(x => new { x.ProductVariantId, x.LanguageCode }); b.Property(x => x.ProductVariantId).Id(x => x.Value, x => new ProductVariantId(x)); b.Property(x => x.LanguageCode).HasMaxLength(2); b.Property(x => x.Name).HasMaxLength(200); } }
internal sealed class OptionGroupConfiguration : IEntityTypeConfiguration<OptionGroup> { public void Configure(EntityTypeBuilder<OptionGroup> b) { b.ToTable("option_groups", CatalogPersistence.Schema, t => { t.HasCheckConstraint("ck_option_groups_limits", "min_selections >= 0 AND max_selections >= 1 AND min_selections <= max_selections"); t.HasCheckConstraint("ck_option_groups_sort", "sort_order >= 0"); }); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new OptionGroupId(x)); b.Property(x => x.ProductId).Id(x => x.Value, x => new ProductId(x)); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.Property(x => x.SelectionType).HasConversion<short>(); b.Property(x => x.CreatedAtUtc).Utc(); b.Property(x => x.UpdatedAtUtc).Utc(); b.Property(x => x.ConcurrencyStamp).IsConcurrencyToken(); b.HasMany(x => x.Translations).WithOne().HasForeignKey(x => x.OptionGroupId).OnDelete(DeleteBehavior.Restrict); b.HasMany(x => x.Options).WithOne().HasForeignKey(x => x.OptionGroupId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class OptionGroupTranslationConfiguration : IEntityTypeConfiguration<OptionGroupTranslation> { public void Configure(EntityTypeBuilder<OptionGroupTranslation> b) { b.ToTable("option_group_translations"); b.HasKey(x => new { x.OptionGroupId, x.LanguageCode }); b.Property(x => x.OptionGroupId).Id(x => x.Value, x => new OptionGroupId(x)); b.Property(x => x.LanguageCode).HasMaxLength(2); b.Property(x => x.Name).HasMaxLength(200); } }
internal sealed class ProductOptionConfiguration : IEntityTypeConfiguration<ProductOption> { public void Configure(EntityTypeBuilder<ProductOption> b) { b.ToTable("product_options", CatalogPersistence.Schema, t => t.HasCheckConstraint("ck_product_options_sort", "sort_order >= 0")); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new ProductOptionId(x)); b.Property(x => x.OptionGroupId).Id(x => x.Value, x => new OptionGroupId(x)); b.Property(x => x.ProductId).Id(x => x.Value, x => new ProductId(x)); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.Property(x => x.CreatedAtUtc).Utc(); b.Property(x => x.UpdatedAtUtc).Utc(); b.Property(x => x.ConcurrencyStamp).IsConcurrencyToken(); b.HasMany(x => x.Translations).WithOne().HasForeignKey(x => x.ProductOptionId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class ProductOptionTranslationConfiguration : IEntityTypeConfiguration<ProductOptionTranslation> { public void Configure(EntityTypeBuilder<ProductOptionTranslation> b) { b.ToTable("product_option_translations"); b.HasKey(x => new { x.ProductOptionId, x.LanguageCode }); b.Property(x => x.ProductOptionId).Id(x => x.Value, x => new ProductOptionId(x)); b.Property(x => x.LanguageCode).HasMaxLength(2); b.Property(x => x.Name).HasMaxLength(200); } }
internal sealed class ProductImageReferenceConfiguration : IEntityTypeConfiguration<ProductImageReference> { public void Configure(EntityTypeBuilder<ProductImageReference> b) { b.ToTable("product_image_references", CatalogPersistence.Schema, t => t.HasCheckConstraint("ck_product_images_reference", "media_id IS NOT NULL OR external_reference IS NOT NULL")); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new ProductImageReferenceId(x)); b.Property(x => x.ProductId).Id(x => x.Value, x => new ProductId(x)); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.Property(x => x.ExternalReference).HasMaxLength(2000); b.Property(x => x.AltText).HasMaxLength(500); b.Property(x => x.CreatedAtUtc).Utc(); b.HasIndex(x => x.ProductId).IsUnique().HasFilter("is_primary = true"); } }
internal sealed class ProductAvailabilityConfiguration : IEntityTypeConfiguration<ProductAvailabilitySchedule> { public void Configure(EntityTypeBuilder<ProductAvailabilitySchedule> b) { b.ToTable("product_availability_schedules"); b.HasKey(x => x.Id); b.Property(x => x.Id).Id(x => x.Value, x => new ProductAvailabilityScheduleId(x)); b.Property(x => x.ProductId).Id(x => x.Value, x => new ProductId(x)); b.Property(x => x.MerchantId).HasColumnType("uuid"); b.Property(x => x.MerchantBranchId).HasColumnType("uuid"); b.Property(x => x.DayOfWeek).HasConversion<short>(); b.Property(x => x.StartLocalTime).HasColumnType("time without time zone"); b.Property(x => x.EndLocalTime).HasColumnType("time without time zone"); b.Property(x => x.TimeZoneId).HasMaxLength(100); b.HasIndex(x => new { x.ProductId, x.MerchantBranchId, x.DayOfWeek }); } }
