<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\AlSsareea.BuildingBlocks.Application\AlSsareea.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\BuildingBlocks\AlSsareea.BuildingBlocks.Infrastructure\AlSsareea.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Identity\AlSsareea.Modules.Identity.Application\AlSsareea.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\Modules\Identity\AlSsareea.Modules.Identity.Infrastructure\AlSsareea.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Maps\AlSsareea.Modules.Maps.Application\AlSsareea.Modules.Maps.Application.csproj" />
    <ProjectReference Include="..\Modules\Maps\AlSsareea.Modules.Maps.Infrastructure\AlSsareea.Modules.Maps.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Customers\AlSsareea.Modules.Customers.Application\AlSsareea.Modules.Customers.Application.csproj" />
    <ProjectReference Include="..\Modules\Customers\AlSsareea.Modules.Customers.Contracts\AlSsareea.Modules.Customers.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Customers\AlSsareea.Modules.Customers.Infrastructure\AlSsareea.Modules.Customers.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Merchants\AlSsareea.Modules.Merchants.Application\AlSsareea.Modules.Merchants.Application.csproj" />
    <ProjectReference Include="..\Modules\Merchants\AlSsareea.Modules.Merchants.Contracts\AlSsareea.Modules.Merchants.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Merchants\AlSsareea.Modules.Merchants.Infrastructure\AlSsareea.Modules.Merchants.Infrastructure.csproj" />
  </ItemGroup>
</Project>
