// <auto-generated />
using System;
using AlSsareea.Modules.Merchants.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Merchants.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MerchantsDbContext))]
    partial class MerchantsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("merchants")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BranchScheduleOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_merchant_branch_schedule_overrides");

                    b.HasIndex("BranchId", "StartDate", "EndDate")
                        .HasDatabaseName("ix_merchant_branch_schedule_overrides_branch_id_start_date_end");

                    b.ToTable("merchant_branch_schedule_overrides", "merchants", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_override_dates", "end_date >= start_date");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BranchServiceArea", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ServiceAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_area_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("BranchId", "ServiceAreaId")
                        .HasName("pk_merchant_branch_service_areas");

                    b.HasIndex("ServiceAreaId")
                        .HasDatabaseName("ix_merchant_branch_service_areas_service_area_id");

                    b.ToTable("merchant_branch_service_areas", "merchants");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BusinessHour", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<bool>("ClosedAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("closed_all_day");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.HasKey("Id")
                        .HasName("pk_merchant_business_hours");

                    b.HasIndex("BranchId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_merchant_business_hours_branch_id_day_of_week");

                    b.ToTable("merchant_business_hours", "merchants", t =>
                        {
                            t.HasCheckConstraint("ck_business_hours_day", "day_of_week BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BusinessHourPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessHourId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_hour_id");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.HasKey("Id")
                        .HasName("pk_merchant_business_hour_periods");

                    b.HasIndex("BusinessHourId", "OpensAt")
                        .HasDatabaseName("ix_merchant_business_hour_periods_business_hour_id_opens_at");

                    b.ToTable("merchant_business_hour_periods", "merchants", t =>
                        {
                            t.HasCheckConstraint("ck_business_hour_period_order", "opens_at < closes_at");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("ClosingReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("closing_reason");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registration_number");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at_utc");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("suspension_reason");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_number");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_merchants");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_merchants_display_name");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_merchants_owner_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_merchants_status");

                    b.ToTable("merchants", "merchants", t =>
                        {
                            t.HasCheckConstraint("ck_merchants_status", "status BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.MerchantBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("ReopenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reopened_at_utc");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StatusChangeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("status_change_reason");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<DateTime?>("TemporarilyClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("temporarily_closed_at_utc");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_merchant_branches");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_merchant_branches_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MerchantId")
                        .IsUnique()
                        .HasDatabaseName("ux_merchant_branches_primary_per_merchant")
                        .HasFilter("is_primary = true");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_merchant_branches_status");

                    b.HasIndex("MerchantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_merchant_branches_merchant_id_code")
                        .HasFilter("code IS NOT NULL");

                    b.ToTable("merchant_branches", "merchants", t =>
                        {
                            t.HasCheckConstraint("ck_merchant_branches_status", "status BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.MerchantEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at_utc");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_merchant_employees");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_merchant_employees_branch_id");

                    b.HasIndex("MerchantId")
                        .IsUnique()
                        .HasDatabaseName("ux_merchant_employees_active_owner")
                        .HasFilter("role = 1 AND status = 2");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_merchant_employees_user_id");

                    b.HasIndex("MerchantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_merchant_employees_active_user")
                        .HasFilter("status <> 4");

                    b.ToTable("merchant_employees", "merchants", t =>
                        {
                            t.HasCheckConstraint("ck_merchant_employees_role", "role BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_merchant_employees_status", "status BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.SpecialHourPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.Property<Guid>("ScheduleOverrideId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_override_id");

                    b.HasKey("Id")
                        .HasName("pk_merchant_branch_special_hour_periods");

                    b.HasIndex("ScheduleOverrideId")
                        .HasDatabaseName("ix_merchant_branch_special_hour_periods_schedule_override_id");

                    b.ToTable("merchant_branch_special_hour_periods", "merchants", t =>
                        {
                            t.HasCheckConstraint("ck_special_hour_period_order", "opens_at < closes_at");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BranchScheduleOverride", b =>
                {
                    b.HasOne("AlSsareea.Modules.Merchants.Domain.MerchantBranch", null)
                        .WithMany("ScheduleOverrides")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_branch_schedule_overrides_merchant_branches_branch");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BranchServiceArea", b =>
                {
                    b.HasOne("AlSsareea.Modules.Merchants.Domain.MerchantBranch", null)
                        .WithMany("ServiceAreas")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_branch_service_areas_merchant_branches_branch_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BusinessHour", b =>
                {
                    b.HasOne("AlSsareea.Modules.Merchants.Domain.MerchantBranch", null)
                        .WithMany("BusinessHours")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_business_hours_merchant_branches_branch_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BusinessHourPeriod", b =>
                {
                    b.HasOne("AlSsareea.Modules.Merchants.Domain.BusinessHour", null)
                        .WithMany("Periods")
                        .HasForeignKey("BusinessHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_business_hour_periods_merchant_business_hours_busi");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.MerchantBranch", b =>
                {
                    b.HasOne("AlSsareea.Modules.Merchants.Domain.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_branches_merchants_merchant_id");

                    b.OwnsOne("AlSsareea.Modules.Merchants.Domain.BranchAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("MerchantBranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Area")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("address_area");

                            b1.Property<string>("BuildingNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_building_number");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("address_city");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.HasKey("MerchantBranchId");

                            b1.ToTable("merchant_branches", "merchants");

                            b1.WithOwner()
                                .HasForeignKey("MerchantBranchId")
                                .HasConstraintName("fk_merchant_branches_merchant_branches_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.MerchantEmployee", b =>
                {
                    b.HasOne("AlSsareea.Modules.Merchants.Domain.MerchantBranch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_merchant_employees_merchant_branches_branch_id");

                    b.HasOne("AlSsareea.Modules.Merchants.Domain.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_employees_merchants_merchant_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.SpecialHourPeriod", b =>
                {
                    b.HasOne("AlSsareea.Modules.Merchants.Domain.BranchScheduleOverride", null)
                        .WithMany("Periods")
                        .HasForeignKey("ScheduleOverrideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merchant_branch_special_hour_periods_merchant_branch_schedu");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BranchScheduleOverride", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.BusinessHour", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("AlSsareea.Modules.Merchants.Domain.MerchantBranch", b =>
                {
                    b.Navigation("BusinessHours");

                    b.Navigation("ScheduleOverrides");

                    b.Navigation("ServiceAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
