// <auto-generated />
using System;
using AlSsareea.Modules.Carts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Carts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CartsDbContext))]
    [Migration("20260729191929_AddCartsModule")]
    partial class AddCartsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("carts")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Carts.Domain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("LastPricedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_priced_at_utc");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_carts_expires_at_utc");

                    b.HasIndex("CustomerId", "MerchantId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ux_carts_active_customer_merchant_branch")
                        .HasFilter("status = 1");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CustomerId", "MerchantId", "BranchId"), false);

                    b.ToTable("carts", "carts");
                });

            modelBuilder.Entity("AlSsareea.Modules.Carts.Domain.CartIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.HasKey("Id")
                        .HasName("pk_cart_idempotency_records");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_cart_idempotency_records_expires_at_utc");

                    b.HasIndex("CustomerId", "Operation", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_cart_idempotency_customer_operation_key");

                    b.ToTable("cart_idempotency_records", "carts");
                });

            modelBuilder.Entity("AlSsareea.Modules.Carts.Domain.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<int>("CatalogVersion")
                        .HasColumnType("integer")
                        .HasColumnName("catalog_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_note");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_cart_items");

                    b.HasIndex("CartId")
                        .HasDatabaseName("ix_cart_items_cart_id");

                    b.ToTable("cart_items", "carts", t =>
                        {
                            t.HasCheckConstraint("ck_cart_items_quantity", "quantity > 0 AND quantity <= 99");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Carts.Domain.CartItemOption", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_item_id");

                    b.Property<Guid>("OptionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_group_id");

                    b.Property<Guid>("OptionItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_item_id");

                    b.Property<int>("CatalogVersion")
                        .HasColumnType("integer")
                        .HasColumnName("catalog_version");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("CartItemId", "OptionGroupId", "OptionItemId")
                        .HasName("pk_cart_item_options");

                    b.ToTable("cart_item_options", "carts", t =>
                        {
                            t.HasCheckConstraint("ck_cart_item_options_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Carts.Domain.CartItem", b =>
                {
                    b.HasOne("AlSsareea.Modules.Carts.Domain.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_items_carts_cart_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Carts.Domain.CartItemOption", b =>
                {
                    b.HasOne("AlSsareea.Modules.Carts.Domain.CartItem", null)
                        .WithMany("SelectedOptions")
                        .HasForeignKey("CartItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_options_cart_items_cart_item_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Carts.Domain.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlSsareea.Modules.Carts.Domain.CartItem", b =>
                {
                    b.Navigation("SelectedOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
