// <auto-generated />
using System;
using AlSsareea.Modules.Customers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Customers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260724103937_AddCustomersModule")]
    partial class AddCustomersModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Customers.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("block_reason");

                    b.Property<DateTime?>("BlockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at_utc");

                    b.Property<Guid?>("BlockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_by_user_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_customers_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_user_id");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_customers_created_at_utc_id");

                    b.HasIndex("UpdatedAtUtc", "Id")
                        .HasDatabaseName("ix_customers_updated_at_utc_id");

                    b.ToTable("customers", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customers_block_metadata", "(status = 3 AND block_reason IS NOT NULL AND blocked_at_utc IS NOT NULL AND blocked_by_user_id IS NOT NULL) OR status <> 3");

                            t.HasCheckConstraint("ck_customers_deleted_status", "(status = 4 AND deleted_at_utc IS NOT NULL) OR (status <> 4 AND deleted_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_customers_status", "status BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Customers.Domain.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AddressType")
                        .HasColumnType("smallint")
                        .HasColumnName("address_type");

                    b.Property<string>("Apartment")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("apartment");

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("area");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("building_number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("city");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("DeliveryInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("delivery_instructions");

                    b.Property<string>("Floor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("floor");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("place_id");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_addresses");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_addresses_active_default")
                        .HasFilter("is_default = true AND deleted_at_utc IS NULL");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_customer_addresses_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("CustomerId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_customer_addresses_customer_id_created_at_utc_id");

                    b.ToTable("customer_addresses", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_addresses_location", "location IS NULL OR ST_SRID(location) = 4326");

                            t.HasCheckConstraint("ck_customer_addresses_type", "address_type BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Customers.Domain.CustomerPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowMarketingNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_marketing_notifications");

                    b.Property<bool>("AllowOrderStatusNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_order_status_notifications");

                    b.Property<bool>("AllowPromotionalNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_promotional_notifications");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("preferred_currency")
                        .IsFixedLength();

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("preferred_language");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_customer_preferences");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_preferences_customer_id");

                    b.ToTable("customer_preferences", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_preferences_currency", "preferred_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_customer_preferences_language", "preferred_language IN ('ar', 'he', 'en')");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Customers.Domain.CustomerStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<short>("NewStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("new_status");

                    b.Property<short>("PreviousStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_customer_status_history");

                    b.HasIndex("CustomerId", "ChangedAtUtc", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_customer_status_history_customer_id_changed_at_utc_id");

                    b.ToTable("customer_status_history", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_status_history_new_status", "new_status BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_customer_status_history_previous_status", "previous_status BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_customer_status_history_reason", "new_status = 1 OR reason IS NOT NULL");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Customers.Domain.CustomerAddress", b =>
                {
                    b.HasOne("AlSsareea.Modules.Customers.Domain.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_addresses_customers_customer_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Customers.Domain.CustomerPreference", b =>
                {
                    b.HasOne("AlSsareea.Modules.Customers.Domain.Customer", null)
                        .WithOne("Preferences")
                        .HasForeignKey("AlSsareea.Modules.Customers.Domain.CustomerPreference", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_preferences_customers_customer_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Customers.Domain.CustomerStatusHistory", b =>
                {
                    b.HasOne("AlSsareea.Modules.Customers.Domain.Customer", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_status_history_customers_customer_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Customers.Domain.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
