// <auto-generated />
using System;
using AlSsareea.Modules.Promotions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Promotions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PromotionsDbContext))]
    partial class PromotionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("promotions")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Promotions.Domain.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("ConflictGroup")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("conflict_group");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_coupon_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("internal_name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<short>("Stackability")
                        .HasColumnType("smallint")
                        .HasColumnName("stackability");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_promotions");

                    b.HasIndex("CouponCode")
                        .IsUnique()
                        .HasDatabaseName("ux_promotions_normalized_coupon_code")
                        .HasFilter("normalized_coupon_code IS NOT NULL");

                    b.HasIndex("InternalName")
                        .IsUnique()
                        .HasDatabaseName("ux_promotions_internal_name");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_promotions_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_promotions_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_promotions_type");

                    b.HasIndex("Status", "Priority")
                        .HasDatabaseName("ix_promotions_active_priority")
                        .HasFilter("status = 2");

                    b.ToTable("promotions", "promotions", t =>
                        {
                            t.HasCheckConstraint("ck_promotions_benefit", "benefit_value >= 0 AND (maximum_discount_minor IS NULL OR maximum_discount_minor >= 0)");

                            t.HasCheckConstraint("ck_promotions_funding", "platform_share_basis_points >= 0 AND merchant_share_basis_points >= 0 AND platform_share_basis_points + merchant_share_basis_points = 10000");

                            t.HasCheckConstraint("ck_promotions_priority", "priority BETWEEN -100000 AND 100000");

                            t.HasCheckConstraint("ck_promotions_status", "status BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_promotions_type", "type BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_promotions_usage_limits", "(global_usage_limit IS NULL OR global_usage_limit > 0) AND (per_customer_usage_limit IS NULL OR per_customer_usage_limit > 0) AND (budget_limit_minor IS NULL OR budget_limit_minor > 0)");

                            t.HasCheckConstraint("ck_promotions_validity", "ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Promotions.Domain.PromotionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.HasKey("Id")
                        .HasName("pk_promotion_audit");

                    b.HasIndex("PromotionId", "OccurredAtUtc")
                        .HasDatabaseName("ix_promotion_audit_promotion_occurred");

                    b.ToTable("promotion_audit", "promotions");
                });

            modelBuilder.Entity("AlSsareea.Modules.Promotions.Domain.PromotionRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<long>("DiscountAmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_amount_minor");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_reference");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.HasKey("Id")
                        .HasName("pk_promotion_redemptions");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_promotion_redemptions_customer_id");

                    b.HasIndex("ExternalReference")
                        .IsUnique()
                        .HasDatabaseName("ux_promotion_redemptions_external_reference");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_promotion_redemptions_promotion_id");

                    b.ToTable("promotion_redemptions", "promotions", t =>
                        {
                            t.HasCheckConstraint("ck_promotion_redemptions_amount", "discount_amount_minor >= 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Promotions.Domain.Promotion", b =>
                {
                    b.OwnsOne("AlSsareea.Modules.Promotions.Domain.DiscountBenefit", "Benefit", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();

                            b1.Property<short>("Kind")
                                .HasColumnType("smallint")
                                .HasColumnName("benefit_kind");

                            b1.Property<long?>("MaximumDiscountMinor")
                                .HasColumnType("bigint")
                                .HasColumnName("maximum_discount_minor");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("benefit_value");

                            b1.HasKey("PromotionId");

                            b1.ToTable("promotions", "promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId")
                                .HasConstraintName("fk_promotions_promotions_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Promotions.Domain.EligibilityRules", "Eligibility", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("eligible_customer_id");

                            b1.Property<bool>("FirstOrderOnly")
                                .HasColumnType("boolean")
                                .HasColumnName("first_order_only");

                            b1.Property<long?>("MinimumSubtotalMinor")
                                .HasColumnType("bigint")
                                .HasColumnName("minimum_subtotal_minor");

                            b1.HasKey("PromotionId");

                            b1.ToTable("promotions", "promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId")
                                .HasConstraintName("fk_promotions_promotions_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Promotions.Domain.FundingPolicy", "Funding", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("MerchantShareBasisPoints")
                                .HasColumnType("integer")
                                .HasColumnName("merchant_share_basis_points");

                            b1.Property<int>("PlatformShareBasisPoints")
                                .HasColumnType("integer")
                                .HasColumnName("platform_share_basis_points");

                            b1.Property<short>("Source")
                                .HasColumnType("smallint")
                                .HasColumnName("funding_source");

                            b1.HasKey("PromotionId");

                            b1.ToTable("promotions", "promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId")
                                .HasConstraintName("fk_promotions_promotions_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Promotions.Domain.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description_en");

                            b1.Property<string>("Hebrew")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description_he");

                            b1.HasKey("PromotionId");

                            b1.ToTable("promotions", "promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId")
                                .HasConstraintName("fk_promotions_promotions_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Promotions.Domain.LocalizedText", "DisplayName", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name_ar");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name_en");

                            b1.Property<string>("Hebrew")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name_he");

                            b1.HasKey("PromotionId");

                            b1.ToTable("promotions", "promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId")
                                .HasConstraintName("fk_promotions_promotions_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Promotions.Domain.PromotionScope", "Scope", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("MerchantId")
                                .HasColumnType("uuid")
                                .HasColumnName("scope_merchant_id");

                            b1.PrimitiveCollection<Guid[]>("TargetIds")
                                .IsRequired()
                                .HasColumnType("uuid[]")
                                .HasColumnName("scope_target_ids");

                            b1.Property<short>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("scope_type");

                            b1.HasKey("PromotionId");

                            b1.HasIndex("MerchantId")
                                .HasDatabaseName("ix_promotions_scope_merchant_id");

                            b1.HasIndex("TargetIds")
                                .HasDatabaseName("ix_promotions_scope_target_ids");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("TargetIds"), "gin");

                            b1.ToTable("promotions", "promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId")
                                .HasConstraintName("fk_promotions_promotions_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Promotions.Domain.UsageLimits", "UsageLimits", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<long?>("BudgetLimitMinor")
                                .HasColumnType("bigint")
                                .HasColumnName("budget_limit_minor");

                            b1.Property<long?>("GlobalLimit")
                                .HasColumnType("bigint")
                                .HasColumnName("global_usage_limit");

                            b1.Property<int?>("MaximumRedemptionsPerOrder")
                                .HasColumnType("integer")
                                .HasColumnName("maximum_redemptions_per_order");

                            b1.Property<long?>("PerCustomerLimit")
                                .HasColumnType("bigint")
                                .HasColumnName("per_customer_usage_limit");

                            b1.HasKey("PromotionId");

                            b1.ToTable("promotions", "promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId")
                                .HasConstraintName("fk_promotions_promotions_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Promotions.Domain.ValidityPeriod", "Validity", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("EndsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ends_at_utc");

                            b1.Property<DateTime>("StartsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("starts_at_utc");

                            b1.HasKey("PromotionId");

                            b1.HasIndex("StartsAtUtc", "EndsAtUtc")
                                .HasDatabaseName("ix_promotions_validity");

                            b1.ToTable("promotions", "promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId")
                                .HasConstraintName("fk_promotions_promotions_id");
                        });

                    b.Navigation("Benefit")
                        .IsRequired();

                    b.Navigation("Description");

                    b.Navigation("DisplayName")
                        .IsRequired();

                    b.Navigation("Eligibility")
                        .IsRequired();

                    b.Navigation("Funding")
                        .IsRequired();

                    b.Navigation("Scope")
                        .IsRequired();

                    b.Navigation("UsageLimits")
                        .IsRequired();

                    b.Navigation("Validity")
                        .IsRequired();
                });

            modelBuilder.Entity("AlSsareea.Modules.Promotions.Domain.PromotionAudit", b =>
                {
                    b.HasOne("AlSsareea.Modules.Promotions.Domain.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_audit_promotions_promotion_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Promotions.Domain.PromotionRedemption", b =>
                {
                    b.HasOne("AlSsareea.Modules.Promotions.Domain.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_redemptions_promotions_promotion_id");
                });
#pragma warning restore 612, 618
        }
    }
}
