// <auto-generated />
using System;
using AlSsareea.Modules.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260726114901_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("default_language");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_catalogs");

                    b.HasIndex("MerchantId")
                        .IsUnique()
                        .HasDatabaseName("ix_catalogs_merchant_id");

                    b.ToTable("catalogs", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_catalogs_status", "status BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.HasIndex("MerchantId", "CatalogId", "SortOrder")
                        .HasDatabaseName("ix_categories_merchant_id_catalog_id_sort_order");

                    b.ToTable("categories", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_categories_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.CategoryTranslation", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language_code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(2200)
                        .HasColumnType("character varying(2200)")
                        .HasColumnName("search_text");

                    b.HasKey("CategoryId", "LanguageCode")
                        .HasName("pk_category_translations");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_category_translations_search_text");

                    b.ToTable("category_translations", "catalog");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.MenuSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AvailableFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_from_utc");

                    b.Property<DateTime?>("AvailableUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_until_utc");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_menu_sections");

                    b.ToTable("menu_sections", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_menu_sections_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.MenuSectionProduct", b =>
                {
                    b.Property<Guid>("MenuSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_section_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("MenuSectionId", "ProductId")
                        .HasName("pk_menu_section_products");

                    b.ToTable("menu_section_products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_menu_section_products_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.MenuSectionTranslation", b =>
                {
                    b.Property<Guid>("MenuSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_section_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language_code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("MenuSectionId", "LanguageCode")
                        .HasName("pk_menu_section_translations");

                    b.ToTable("menu_section_translations", "catalog");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.OptionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("integer")
                        .HasColumnName("max_selections");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<int>("MinSelections")
                        .HasColumnType("integer")
                        .HasColumnName("min_selections");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<short>("SelectionType")
                        .HasColumnType("smallint")
                        .HasColumnName("selection_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_option_groups");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_option_groups_product_id");

                    b.ToTable("option_groups", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_option_groups_limits", "min_selections >= 0 AND max_selections >= 1 AND min_selections <= max_selections");

                            t.HasCheckConstraint("ck_option_groups_sort", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.OptionGroupTranslation", b =>
                {
                    b.Property<Guid>("OptionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_group_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("OptionGroupId", "LanguageCode")
                        .HasName("pk_option_group_translations");

                    b.ToTable("option_group_translations", "catalog");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BasePriceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("base_price_minor");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.Property<short>("InventoryStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("inventory_status");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TaxCategoryReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_category_reference");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("MerchantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_merchant_id_sku")
                        .HasFilter("sku IS NOT NULL");

                    b.HasIndex("MerchantId", "Status", "InventoryStatus", "IsVisible", "SortOrder")
                        .HasDatabaseName("ix_products_merchant_id_status_inventory_status_is_visible_sor");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_products_price", "base_price_minor >= 0");

                            t.HasCheckConstraint("ck_products_sort", "sort_order >= 0");

                            t.HasCheckConstraint("ck_products_version", "current_version >= 1");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductAvailabilitySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_local_time");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid?>("MerchantBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_branch_id");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<TimeOnly>("StartLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_local_time");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_product_availability_schedules");

                    b.HasIndex("ProductId", "MerchantBranchId", "DayOfWeek")
                        .HasDatabaseName("ix_product_availability_schedules_product_id_merchant_branch_i");

                    b.ToTable("product_availability_schedules", "catalog");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductImageReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alt_text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("external_reference");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_product_image_references");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_image_references_product_id")
                        .HasFilter("is_primary = true");

                    b.ToTable("product_image_references", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_images_reference", "media_id IS NOT NULL OR external_reference IS NOT NULL");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid>("OptionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_group_id");

                    b.Property<long>("PriceAdjustmentMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("price_adjustment_minor");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_product_options");

                    b.HasIndex("OptionGroupId")
                        .HasDatabaseName("ix_product_options_option_group_id");

                    b.ToTable("product_options", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_options_sort", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductOptionTranslation", b =>
                {
                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("ProductOptionId", "LanguageCode")
                        .HasName("pk_product_option_translations");

                    b.ToTable("product_option_translations", "catalog");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductTranslation", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language_code");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(4200)
                        .HasColumnType("character varying(4200)")
                        .HasColumnName("search_text");

                    b.HasKey("ProductId", "LanguageCode")
                        .HasName("pk_product_translations");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_product_translations_search_text");

                    b.ToTable("product_translations", "catalog");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<short>("InventoryStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("inventory_status");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<long>("PriceAdjustmentMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("price_adjustment_minor");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_variants_product_id")
                        .HasFilter("is_default = true");

                    b.HasIndex("MerchantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_product_variants_merchant_id_sku")
                        .HasFilter("sku IS NOT NULL");

                    b.ToTable("product_variants", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_variants_sort", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductVariantTranslation", b =>
                {
                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("ProductVariantId", "LanguageCode")
                        .HasName("pk_product_variant_translations");

                    b.ToTable("product_variant_translations", "catalog");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.Category", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.CategoryTranslation", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.Category", null)
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_translations_categories_category_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.MenuSectionProduct", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.MenuSection", null)
                        .WithMany("Products")
                        .HasForeignKey("MenuSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_section_products_menu_sections_menu_section_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.MenuSectionTranslation", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.MenuSection", null)
                        .WithMany("Translations")
                        .HasForeignKey("MenuSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_section_translations_menu_sections_menu_section_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.OptionGroup", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.Product", null)
                        .WithMany("OptionGroups")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_option_groups_products_product_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.OptionGroupTranslation", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.OptionGroup", null)
                        .WithMany("Translations")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_option_group_translations_option_groups_option_group_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductAvailabilitySchedule", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.Product", null)
                        .WithMany("Availability")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_availability_schedules_products_product_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductImageReference", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_image_references_products_product_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductOption", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.OptionGroup", null)
                        .WithMany("Options")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_options_option_groups_option_group_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductOptionTranslation", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.ProductOption", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_option_translations_product_options_product_option_");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductTranslation", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.Product", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_translations_products_product_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductVariant", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductVariantTranslation", b =>
                {
                    b.HasOne("AlSsareea.Modules.Catalog.Domain.ProductVariant", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_translations_product_variants_product_varia");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.Category", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.MenuSection", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.OptionGroup", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.Product", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Images");

                    b.Navigation("OptionGroups");

                    b.Navigation("Translations");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductOption", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AlSsareea.Modules.Catalog.Domain.ProductVariant", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
