// <auto-generated />
using System;
using AlSsareea.Modules.Notifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260828121329_InitializeNotificationsModule")]
    partial class InitializeNotificationsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("deactivation_reason");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short>("Platform")
                        .HasColumnType("smallint")
                        .HasColumnName("platform");

                    b.Property<short>("Provider")
                        .HasColumnType("smallint")
                        .HasColumnName("provider");

                    b.Property<string>("TokenCiphertext")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("token_ciphertext");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenMask")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("token_mask");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_device_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_device_tokens_token_hash");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_notification_device_tokens_user_id_is_active");

                    b.ToTable("notification_device_tokens", "notifications", t =>
                        {
                            t.HasCheckConstraint("ck_notification_device_tokens_platform", "platform BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_notification_device_tokens_provider", "provider BETWEEN 1 AND 2");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("template_key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_notifications_user_id_created_at_utc");

                    b.HasIndex("UserId", "ReadAtUtc")
                        .HasDatabaseName("ix_notifications_user_id_read_at_utc")
                        .HasFilter("channel = 4");

                    b.HasIndex("SourceEventId", "UserId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_source_event_id_user_id_channel");

                    b.ToTable("notifications", "notifications", t =>
                        {
                            t.HasCheckConstraint("ck_notifications_body", "char_length(body) > 0");

                            t.HasCheckConstraint("ck_notifications_channel", "channel BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_notifications_status", "status BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.NotificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("error_code");

                    b.Property<short>("FailureKind")
                        .HasColumnType("smallint")
                        .HasColumnName("failure_kind");

                    b.Property<Guid>("NotificationDeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_delivery_id");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("provider_message_id");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id")
                        .HasName("pk_notification_attempts");

                    b.HasIndex("NotificationDeliveryId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_attempts_notification_delivery_id_attempt_numb");

                    b.ToTable("notification_attempts", "notifications");
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DeviceTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_token_id");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("last_error_code");

                    b.Property<int>("MaximumAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_attempts");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_notification_deliveries");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_notification_deliveries_notification_id");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_notification_deliveries_status_next_attempt_at_utc");

                    b.ToTable("notification_deliveries", "notifications", t =>
                        {
                            t.HasCheckConstraint("ck_notification_deliveries_attempts", "attempt_count >= 0 AND attempt_count <= maximum_attempts");

                            t.HasCheckConstraint("ck_notification_deliveries_status", "status BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_preferences");

                    b.HasIndex("UserId", "Category", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_preferences_user_id_category_channel");

                    b.ToTable("notification_preferences", "notifications");
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Subject")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_notification_templates");

                    b.HasIndex("Key", "Channel", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_templates_key_channel_language");

                    b.ToTable("notification_templates", "notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c045063d-1e40-3afb-1b22-489b3b26818f"),
                            Body = "تم استلام طلبك {{orderNumber}}",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.customer",
                            Language = "ar",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e31c4320-95b7-81f9-4a5e-8d3c2ea9dd49"),
                            Body = "تم استلام طلبك {{orderNumber}}",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.customer",
                            Language = "ar",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f7195098-80e4-1a4b-bf03-1a0dc6d6dc32"),
                            Body = "ההזמנה שלך {{orderNumber}} התקבלה",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.customer",
                            Language = "he",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("37ec47bd-a66e-d796-11ff-db75a1e9e59b"),
                            Body = "ההזמנה שלך {{orderNumber}} התקבלה",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.customer",
                            Language = "he",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("490faf13-beba-4937-f1af-7c4224c251d7"),
                            Body = "Your order {{orderNumber}} was received",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.customer",
                            Language = "en",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bcfbfb54-6826-44f8-aa2d-92312c249bbc"),
                            Body = "Your order {{orderNumber}} was received",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.customer",
                            Language = "en",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("46898ce7-2c97-2f10-3061-228aae724339"),
                            Body = "طلب جديد {{orderNumber}}",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.merchant",
                            Language = "ar",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("edfcd08b-7c97-2238-b208-d38916cd01a5"),
                            Body = "طلب جديد {{orderNumber}}",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.merchant",
                            Language = "ar",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ebe72aff-0d49-b900-75ff-a38ac743c199"),
                            Body = "הזמנה חדשה {{orderNumber}}",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.merchant",
                            Language = "he",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("716eea16-4642-a5d8-54d2-c9aa7049950e"),
                            Body = "הזמנה חדשה {{orderNumber}}",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.merchant",
                            Language = "he",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e11cbb2e-95fc-bc24-8126-ffeeccbaa519"),
                            Body = "New order {{orderNumber}}",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.merchant",
                            Language = "en",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("990934b4-6440-5da5-c07f-b128d487dc74"),
                            Body = "New order {{orderNumber}}",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "order.created.merchant",
                            Language = "en",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("89c83315-8089-20e9-9370-dbfd4e91e741"),
                            Body = "تحديث التوصيل للطلب {{orderId}}",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "delivery.status.customer",
                            Language = "ar",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ff07757b-32be-afe8-a16d-5abed9b518e7"),
                            Body = "تحديث التوصيل للطلب {{orderId}}",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "delivery.status.customer",
                            Language = "ar",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0c7992c4-afe1-2ffd-244f-d97dd839709d"),
                            Body = "עדכון משלוח להזמנה {{orderId}}",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "delivery.status.customer",
                            Language = "he",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c4e35bb4-cca1-1f82-473c-4527935b276a"),
                            Body = "עדכון משלוח להזמנה {{orderId}}",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "delivery.status.customer",
                            Language = "he",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("834732b2-f6df-1bb0-d262-c140a23b7d57"),
                            Body = "Delivery update for order {{orderId}}",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "delivery.status.customer",
                            Language = "en",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ec96469e-5266-37b5-7d46-59d08b007f54"),
                            Body = "Delivery update for order {{orderId}}",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "delivery.status.customer",
                            Language = "en",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f50a4478-2f9d-04d3-bfcf-0577f0e56b87"),
                            Body = "لديك عرض توصيل جديد",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "dispatch.offer.driver",
                            Language = "ar",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ff4cd443-7adc-daeb-1e4d-38afa68493f5"),
                            Body = "لديك عرض توصيل جديد",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "dispatch.offer.driver",
                            Language = "ar",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("acc212c4-1350-d3b3-b2cf-cdbfcceb9044"),
                            Body = "יש לך הצעת משלוח חדשה",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "dispatch.offer.driver",
                            Language = "he",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("574f7d2c-4db0-6c53-2bb5-6a32c2eac25f"),
                            Body = "יש לך הצעת משלוח חדשה",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "dispatch.offer.driver",
                            Language = "he",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6fa6c8b3-df88-15e5-9c5d-e10d81c25c96"),
                            Body = "You have a new delivery offer",
                            Channel = (short)4,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "dispatch.offer.driver",
                            Language = "en",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("562a4ec8-26d5-3b7e-cfd5-242523f7c508"),
                            Body = "You have a new delivery offer",
                            Channel = (short)1,
                            CreatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Key = "dispatch.offer.driver",
                            Language = "en",
                            UpdatedAtUtc = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Infrastructure.Persistence.NotificationAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("detail");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_audit");

                    b.HasIndex("UserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_notification_audit_user_id_occurred_at_utc");

                    b.ToTable("notification_audit", "notifications");
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Infrastructure.Persistence.NotificationInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_notification_inbox_messages");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_notification_inbox_messages_processed_at_utc");

                    b.ToTable("notification_inbox_messages", "notifications");
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Infrastructure.Persistence.NotificationOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("error_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_notification_outbox_messages");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_notification_outbox_messages_processed_at_utc_occurred_at_u")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("notification_outbox_messages", "notifications", t =>
                        {
                            t.HasCheckConstraint("ck_notification_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_notification_outbox_payload", "jsonb_typeof(payload) = 'object'");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.NotificationAttempt", b =>
                {
                    b.HasOne("AlSsareea.Modules.Notifications.Domain.NotificationDelivery", null)
                        .WithMany("Attempts")
                        .HasForeignKey("NotificationDeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_notification_attempts_notification_deliveries_notification_");
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.NotificationDelivery", b =>
                {
                    b.HasOne("AlSsareea.Modules.Notifications.Domain.Notification", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_notification_deliveries_notifications_notification_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.Notification", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("AlSsareea.Modules.Notifications.Domain.NotificationDelivery", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
