<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Carts\AlSsareea.Modules.Carts.Application\AlSsareea.Modules.Carts.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Carts\AlSsareea.Modules.Carts.Contracts\AlSsareea.Modules.Carts.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Carts\AlSsareea.Modules.Carts.Domain\AlSsareea.Modules.Carts.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Carts\AlSsareea.Modules.Carts.Infrastructure\AlSsareea.Modules.Carts.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\AlSsareea.Modules.Orders.Application\AlSsareea.Modules.Orders.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\AlSsareea.Modules.Orders.Contracts\AlSsareea.Modules.Orders.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\AlSsareea.Modules.Orders.Domain\AlSsareea.Modules.Orders.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\AlSsareea.Modules.Orders.Infrastructure\AlSsareea.Modules.Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\AlSsareea.Api\AlSsareea.Api.csproj" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\AlSsareea.BuildingBlocks.Application\AlSsareea.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\AlSsareea.BuildingBlocks.Domain\AlSsareea.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\AlSsareea.BuildingBlocks.Infrastructure\AlSsareea.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\AlSsareea.Modules.Identity.Application\AlSsareea.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\AlSsareea.Modules.Identity.Contracts\AlSsareea.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\AlSsareea.Modules.Identity.Domain\AlSsareea.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\AlSsareea.Modules.Identity.Infrastructure\AlSsareea.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Maps\AlSsareea.Modules.Maps.Application\AlSsareea.Modules.Maps.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Maps\AlSsareea.Modules.Maps.Contracts\AlSsareea.Modules.Maps.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Maps\AlSsareea.Modules.Maps.Domain\AlSsareea.Modules.Maps.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Maps\AlSsareea.Modules.Maps.Infrastructure\AlSsareea.Modules.Maps.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\AlSsareea.Modules.Customers.Application\AlSsareea.Modules.Customers.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\AlSsareea.Modules.Customers.Contracts\AlSsareea.Modules.Customers.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\AlSsareea.Modules.Customers.Domain\AlSsareea.Modules.Customers.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customers\AlSsareea.Modules.Customers.Infrastructure\AlSsareea.Modules.Customers.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Merchants\AlSsareea.Modules.Merchants.Application\AlSsareea.Modules.Merchants.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Merchants\AlSsareea.Modules.Merchants.Contracts\AlSsareea.Modules.Merchants.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Merchants\AlSsareea.Modules.Merchants.Domain\AlSsareea.Modules.Merchants.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Merchants\AlSsareea.Modules.Merchants.Infrastructure\AlSsareea.Modules.Merchants.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\AlSsareea.Modules.Catalog.Application\AlSsareea.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\AlSsareea.Modules.Catalog.Contracts\AlSsareea.Modules.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\AlSsareea.Modules.Catalog.Domain\AlSsareea.Modules.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\AlSsareea.Modules.Catalog.Infrastructure\AlSsareea.Modules.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Media\AlSsareea.Modules.Media.Application\AlSsareea.Modules.Media.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Media\AlSsareea.Modules.Media.Contracts\AlSsareea.Modules.Media.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Media\AlSsareea.Modules.Media.Domain\AlSsareea.Modules.Media.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Media\AlSsareea.Modules.Media.Infrastructure\AlSsareea.Modules.Media.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pricing\AlSsareea.Modules.Pricing.Application\AlSsareea.Modules.Pricing.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pricing\AlSsareea.Modules.Pricing.Contracts\AlSsareea.Modules.Pricing.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pricing\AlSsareea.Modules.Pricing.Domain\AlSsareea.Modules.Pricing.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pricing\AlSsareea.Modules.Pricing.Infrastructure\AlSsareea.Modules.Pricing.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Promotions\AlSsareea.Modules.Promotions.Application\AlSsareea.Modules.Promotions.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Promotions\AlSsareea.Modules.Promotions.Contracts\AlSsareea.Modules.Promotions.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Promotions\AlSsareea.Modules.Promotions.Domain\AlSsareea.Modules.Promotions.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Promotions\AlSsareea.Modules.Promotions.Infrastructure\AlSsareea.Modules.Promotions.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
