// <auto-generated />
using System;
using AlSsareea.Modules.Pricing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Pricing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    partial class PricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Pricing.Domain.PricingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTime?>("EffectiveUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until_utc");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("scope_key");

                    b.Property<short>("ScopeType")
                        .HasColumnType("smallint")
                        .HasColumnName("scope_type");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_pricing_policies");

                    b.HasIndex("MerchantId", "BranchId")
                        .HasDatabaseName("ix_pricing_policies_merchant_id_branch_id");

                    b.HasIndex("Status", "Currency", "EffectiveFromUtc", "EffectiveUntilUtc")
                        .HasDatabaseName("ix_pricing_policies_status_currency_effective_from_utc_effecti");

                    b.HasIndex("ScopeKey", "Currency", "Status", "Priority", "EffectiveFromUtc")
                        .HasDatabaseName("ix_pricing_policies_scope_key_currency_status_priority_effecti");

                    b.ToTable("pricing_policies", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_pricing_policies_period", "effective_until_utc IS NULL OR effective_until_utc > effective_from_utc");

                            t.HasCheckConstraint("ck_pricing_policies_priority", "priority BETWEEN 0 AND 1000");

                            t.HasCheckConstraint("ck_pricing_policies_scope", "(scope_type = 1 AND merchant_id IS NULL AND branch_id IS NULL AND zone_id IS NULL) OR (scope_type = 2 AND merchant_id IS NULL AND branch_id IS NULL AND zone_id IS NOT NULL) OR (scope_type = 3 AND merchant_id IS NOT NULL AND branch_id IS NULL AND zone_id IS NULL) OR (scope_type = 4 AND merchant_id IS NOT NULL AND branch_id IS NOT NULL AND zone_id IS NULL)");

                            t.HasCheckConstraint("ck_pricing_policies_scope_type", "scope_type BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_pricing_policies_status", "status BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_pricing_policies_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Pricing.Domain.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AdditionalFeePerKilometerMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("additional_fee_per_kilometer_minor");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<short>("CalculationBase")
                        .HasColumnType("smallint")
                        .HasColumnName("calculation_base");

                    b.Property<int?>("IncludedDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("included_distance_meters");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<int?>("MaximumDistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_distance_meters");

                    b.Property<long?>("MaximumMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("maximum_minor");

                    b.Property<long?>("MinimumMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("minimum_minor");

                    b.Property<int>("PercentageBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("percentage_basis_points");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<long?>("ThresholdMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("threshold_minor");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<Guid>("pricing_policy_id")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_policy_id");

                    b.HasKey("Id")
                        .HasName("pk_pricing_rules");

                    b.HasIndex("pricing_policy_id", "Type", "Priority")
                        .HasDatabaseName("ix_pricing_rules_pricing_policy_id_type_priority");

                    b.ToTable("pricing_rules", "pricing", t =>
                        {
                            t.HasCheckConstraint("ck_pricing_rules_amount", "amount_minor >= 0");

                            t.HasCheckConstraint("ck_pricing_rules_base", "calculation_base BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_pricing_rules_distance", "(included_distance_meters IS NULL OR included_distance_meters >= 0) AND (maximum_distance_meters IS NULL OR maximum_distance_meters > 0) AND (additional_fee_per_kilometer_minor IS NULL OR additional_fee_per_kilometer_minor >= 0)");

                            t.HasCheckConstraint("ck_pricing_rules_kind", "kind BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_pricing_rules_money_limits", "(threshold_minor IS NULL OR threshold_minor >= 0) AND (minimum_minor IS NULL OR minimum_minor >= 0) AND (maximum_minor IS NULL OR maximum_minor >= 0) AND (minimum_minor IS NULL OR maximum_minor IS NULL OR minimum_minor <= maximum_minor)");

                            t.HasCheckConstraint("ck_pricing_rules_percentage", "percentage_basis_points BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_pricing_rules_priority", "priority BETWEEN 0 AND 1000");

                            t.HasCheckConstraint("ck_pricing_rules_type", "type BETWEEN 1 AND 8");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Pricing.Domain.PricingRule", b =>
                {
                    b.HasOne("AlSsareea.Modules.Pricing.Domain.PricingPolicy", null)
                        .WithMany("Rules")
                        .HasForeignKey("pricing_policy_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pricing_rules_pricing_policies_pricing_policy_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Pricing.Domain.PricingPolicy", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
