// <auto-generated />
using System;
using AlSsareea.Modules.Delivery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlSsareea.Modules.Delivery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delivery")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Domain.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArrivedAtDropOffAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_at_drop_off_at_utc");

                    b.Property<DateTime?>("ArrivedAtPickupAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_at_pickup_at_utc");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at_utc");

                    b.Property<string>("FailureNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_notes");

                    b.Property<short?>("FailureReason")
                        .HasColumnType("smallint")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime?>("HeadingToPickupAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heading_to_pickup_at_utc");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PickedUpAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at_utc");

                    b.Property<int>("PinFailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("pin_failed_attempts");

                    b.Property<string>("PinHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pin_hash");

                    b.Property<bool>("PinLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("pin_locked");

                    b.Property<string>("PinSalt")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pin_salt");

                    b.Property<short>("ProofRequirements")
                        .HasColumnType("smallint")
                        .HasColumnName("proof_requirements");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_deliveries_customer_id");

                    b.HasIndex("CustomerUserId")
                        .HasDatabaseName("ix_deliveries_customer_user_id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_deliveries_driver_id");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_deliveries_merchant_id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_deliveries_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deliveries_status");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("ix_deliveries_customer_status");

                    b.HasIndex("DriverId", "Status")
                        .HasDatabaseName("ix_deliveries_driver_status");

                    b.ToTable("deliveries", "delivery", t =>
                        {
                            t.HasCheckConstraint("ck_deliveries_driver_assignment", "driver_id IS NULL OR assigned_at_utc IS NOT NULL");

                            t.HasCheckConstraint("ck_deliveries_pin_attempts", "pin_failed_attempts BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_deliveries_pin_configuration", "(proof_requirements & 1) = 0 OR pin_hash IS NOT NULL AND pin_salt IS NOT NULL");

                            t.HasCheckConstraint("ck_deliveries_proof_requirements", "proof_requirements BETWEEN 0 AND 15");

                            t.HasCheckConstraint("ck_deliveries_status", "status BETWEEN 1 AND 10");

                            t.HasCheckConstraint("ck_deliveries_terminal_timestamps", "(status <> 8 OR delivered_at_utc IS NOT NULL) AND (status <> 9 OR failed_at_utc IS NOT NULL) AND (status <> 10 OR cancelled_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Domain.DeliveryProof", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient_name");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_delivery_proofs");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_delivery_proofs_media_asset_id");

                    b.HasIndex("DeliveryId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_delivery_proofs_delivery_type");

                    b.ToTable("delivery_proofs", "delivery", t =>
                        {
                            t.HasCheckConstraint("ck_delivery_proofs_content", "(type IN (2,3) AND media_asset_id IS NOT NULL AND recipient_name IS NULL) OR (type = 4 AND media_asset_id IS NULL AND recipient_name IS NOT NULL) OR (type = 1 AND media_asset_id IS NULL AND recipient_name IS NULL)");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Domain.DeliveryStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<short>("NewStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("new_status");

                    b.Property<short?>("PreviousStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("previous_status");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ReasonText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason_text");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_delivery_status_history");

                    b.HasIndex("DeliveryId", "ChangedAtUtc")
                        .HasDatabaseName("ix_delivery_status_history_delivery_changed");

                    b.ToTable("delivery_status_history", "delivery", t =>
                        {
                            t.HasCheckConstraint("ck_delivery_status_history_changed", "previous_status IS NULL OR previous_status <> new_status");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Infrastructure.Persistence.DeliveryAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key_hash");

                    b.Property<short>("NewStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("new_status");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<short>("OldStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("old_status");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("SafeReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("safe_reason_code");

                    b.HasKey("Id")
                        .HasName("pk_delivery_audit");

                    b.HasIndex("DeliveryId", "OccurredAtUtc")
                        .HasDatabaseName("ix_delivery_audit_delivery_occurred");

                    b.ToTable("delivery_audit", "delivery", t =>
                        {
                            t.HasCheckConstraint("ck_delivery_audit_key_hash", "char_length(idempotency_key_hash) = 64");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Infrastructure.Persistence.DeliveryOperationIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.HasKey("Id")
                        .HasName("pk_delivery_operation_idempotency");

                    b.HasIndex("DeliveryId")
                        .HasDatabaseName("ix_delivery_idempotency_delivery_id");

                    b.HasIndex("ActorId", "Operation", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_delivery_idempotency_actor_operation_key");

                    b.ToTable("delivery_operation_idempotency", "delivery", t =>
                        {
                            t.HasCheckConstraint("ck_delivery_idempotency_hashes", "char_length(key_hash) = 64 AND char_length(request_hash) = 64");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Infrastructure.Persistence.DeliveryOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_delivery_outbox_messages");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_delivery_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", "delivery", t =>
                        {
                            t.HasCheckConstraint("ck_delivery_outbox_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_delivery_outbox_payload", "jsonb_typeof(payload) = 'object'");
                        });
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Domain.Delivery", b =>
                {
                    b.OwnsOne("AlSsareea.Modules.Delivery.Domain.DropOffSnapshot", "DropOff", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("drop_off_address");

                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid")
                                .HasColumnName("drop_off_address_id");

                            b1.Property<string>("Floor")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("drop_off_floor");

                            b1.Property<string>("Instructions")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("drop_off_instructions");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("drop_off_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("drop_off_longitude");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("drop_off_phone_number");

                            b1.Property<string>("RecipientName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("drop_off_recipient_name");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.OwnsOne("AlSsareea.Modules.Delivery.Domain.PickupSnapshot", "Pickup", b1 =>
                        {
                            b1.Property<Guid>("DeliveryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("pickup_address");

                            b1.Property<Guid?>("BranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("pickup_branch_id");

                            b1.Property<string>("ContactName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("pickup_contact_name");

                            b1.Property<string>("Instructions")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("pickup_instructions");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_longitude");

                            b1.Property<Guid>("MerchantId")
                                .HasColumnType("uuid")
                                .HasColumnName("pickup_merchant_id");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("pickup_phone_number");

                            b1.HasKey("DeliveryId");

                            b1.ToTable("deliveries", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryId")
                                .HasConstraintName("fk_deliveries_deliveries_id");
                        });

                    b.Navigation("DropOff")
                        .IsRequired();

                    b.Navigation("Pickup")
                        .IsRequired();
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Domain.DeliveryProof", b =>
                {
                    b.HasOne("AlSsareea.Modules.Delivery.Domain.Delivery", null)
                        .WithMany("Proofs")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_proofs_deliveries_delivery_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Domain.DeliveryStatusHistory", b =>
                {
                    b.HasOne("AlSsareea.Modules.Delivery.Domain.Delivery", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_status_history_deliveries_delivery_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Infrastructure.Persistence.DeliveryAuditRecord", b =>
                {
                    b.HasOne("AlSsareea.Modules.Delivery.Domain.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_audit_deliveries_delivery_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Infrastructure.Persistence.DeliveryOperationIdempotencyRecord", b =>
                {
                    b.HasOne("AlSsareea.Modules.Delivery.Domain.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_idempotency_deliveries_delivery_id");
                });

            modelBuilder.Entity("AlSsareea.Modules.Delivery.Domain.Delivery", b =>
                {
                    b.Navigation("Proofs");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
